// Message2Client
syntax = "proto3";
package protobuf;

import "MessageType.proto";

message MessageOfCharacter
{
    int64 guid = 1;

    int64 team_id = 2;
    int64 player_id = 3;

    CharacterType character_type = 4;

    // 主动状态
    CharacterState character_active_state = 5;

    // 位置
    int32 x = 6;
    int32 y = 7;

    double facing_direction = 8;
    int32 speed = 9;
    int32 view_range = 10;

    int32 common_attack = 11;
    int64 common_attack_cd = 12;
    int32 common_attack_range = 13;

    int32 hp = 14; 
}


message MessageOfMaterialResource
{
    MaterialResourceState material_resource_state = 1;

    int32 x = 2;
    int32 y = 3;

    int32 process = 4; // 采集进度 等价于血量

    int32 id = 5;

}

message MessageOfMap
{
    uint32 height = 1;
    uint32 width = 2;
    message Row
    {
        repeated PlaceType cols = 1;
    }
    repeated Row rows = 3;
}

message MessageOfTeam
{
    int64 team_id = 1;
    int64 player_id = 2;
    int64 score = 3;
    int64 energy = 4;
//    int64 guid=5;
}

message MessageOfObj
{
    oneof message_of_obj
    {
        MessageOfCharacter character_message = 1;
        MessageOfMaterialResource material_resource_message= 2;
        MessageOfMap map_message = 3;
        MessageOfNews news_message = 4;
        MessageOfTeam team_message = 5;
    }
}

message MessageOfAll
{
    int32 game_time = 1;

    int32 team1_score=2;
    int32 team2_score=3;
    int32 team3_score=4;
    int32 team4_score=5;

    int32 team1_material = 6;
    int32 team2_material = 7;
    int32 team3_material = 8;
    int32 team4_material = 9;

    int32 team1_computing_power = 10;
    int32 team2_computing_power = 11;
    int32 team3_computing_power = 12;
    int32 team4_computing_power = 13;

    int32 team1_factory_hp = 14;
    int32 team2_factory_hp = 15;
    int32 team3_factory_hp = 16;
    int32 team4_factory_hp = 17;

}

message MessageToClient
{
    repeated MessageOfObj obj_message = 1;
    GameState game_state = 2;
    MessageOfAll all_message = 3;
}

message MoveRes // 如果打算设计撞墙保留平行速度分量，且需要返回值则可用这个（大概没啥用）
{
    int64 actual_speed = 1;
    double actual_angle = 2;
    bool act_success = 3;
}

message CreatCharacterRes
{
    bool act_success = 1;
    int64 player_id = 2;
}

message BoolRes
{
    bool act_success = 1;
}

message CharacterInfoRes
{
    repeated MessageOfCharacter Character_info = 1;
}

message EcoRes
{
    int64 economy = 1;
}

message MessageOfNews
{
    oneof news // 一条新闻
    {
        string text_message = 1;
        bytes binary_message = 2;
    }
    int64 from_id = 3;
    int64 to_id = 4;
    int64 team_id = 5;
}
// message MsgRes // 用于获取队友发来的消息
// {
//     bool have_message = 1; // 是否有待接收的消息
//     int64 from_player_id = 2;
//     string message_received = 3;
// }
