syntax = "proto3";
package protobuf;

import "Message2Clients.proto";
import "Message2Server.proto";

service AvailableService
{
    // 连接和初始化服务
    rpc TryConnection(IDMsg) returns (BoolRes);

    // 游戏开局调用一次的服务
    rpc RegisterFactory(RegisterFactoryMsg) returns (stream MessageToClient); // 连接上后等待游戏开始，server会定时通过该服务向所有client发送消息
    rpc GetMap(NullRequest) returns (MessageOfMap);

    // 游戏过程中普通角色执行操作的服务
    rpc Move(MoveMsg) returns (MoveRes);                            // 移动
    rpc Recover(RecoverMsg) returns (BoolRes);                      // 回复
    rpc Harvest(ResourceMsg) returns (BoolRes);                     // 开采原料资源
    rpc Attack(AttackMsg) returns (BoolRes);                        // 普通攻击
    rpc Occupy(OccupyMsg) returns (BoolRes);                        // 占领算力中心
    // rpc AttackConstruction(AttackFactoryMsg) returns (BoolRes);     // 攻击工厂（基地）
    rpc Send(SendMsg) returns (BoolRes);                            // 传递信息
    rpc Load(LoadMsg) returns (BoolRes);                            // 装载产品
    rpc Trade(TradeMsg) returns (BoolRes);                            // 出售产品

    // 游戏过程中核心角色（工厂）可以执行操作的服务
    rpc CreateCharacter(CreateCharacterMsg) returns (BoolRes);        // 创建角色
    rpc CreateCharacterRID(CreateCharacterMsg) returns (CreatCharacterRes); // 获取角色编号
    rpc Produce(ProduceGoodsMsg) returns (BoolRes);               // 生产产品
    //rpc Repair(RepairFactoryMsg) returns (BoolRes);                    // 修理工厂
    rpc EndAllAction(IDMsg) returns (BoolRes);                      // 结束所有动作

    // 智慧大脑
    rpc AskAI(StrategicAIRequest) returns (StrategicAIResponse);      // 客户端请求AI建议
}