// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageType.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_MessageType_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_MessageType_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MessageType_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_MessageType_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MessageType_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace protobuf {

enum GameMode : int {
  NULL_GAME_MODE = 0,
  GAME_MODE_PVE = 1,
  GAME_MODE_PVP = 2,
  GameMode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  GameMode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool GameMode_IsValid(int value);
constexpr GameMode GameMode_MIN = NULL_GAME_MODE;
constexpr GameMode GameMode_MAX = GAME_MODE_PVP;
constexpr int GameMode_ARRAYSIZE = GameMode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GameMode_descriptor();
template<typename T>
inline const std::string& GameMode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, GameMode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function GameMode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    GameMode_descriptor(), enum_t_value);
}
inline bool GameMode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, GameMode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<GameMode>(
    GameMode_descriptor(), name, value);
}
enum GameState : int {
  NULL_GAME_STATE = 0,
  GAME_START = 1,
  GAME_RUNNING = 2,
  GAME_END = 3,
  GameState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  GameState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool GameState_IsValid(int value);
constexpr GameState GameState_MIN = NULL_GAME_STATE;
constexpr GameState GameState_MAX = GAME_END;
constexpr int GameState_ARRAYSIZE = GameState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GameState_descriptor();
template<typename T>
inline const std::string& GameState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, GameState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function GameState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    GameState_descriptor(), enum_t_value);
}
inline bool GameState_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, GameState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<GameState>(
    GameState_descriptor(), name, value);
}
enum PlaceType : int {
  NULL_PLACE_TYPE = 0,
  FACTORY = 1,
  SPACE = 2,
  BARRIER = 3,
  BUSH = 4,
  RESOURCE = 5,
  COMPUTE_CENTER = 6,
  MARKET = 7,
  PlaceType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  PlaceType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool PlaceType_IsValid(int value);
constexpr PlaceType PlaceType_MIN = NULL_PLACE_TYPE;
constexpr PlaceType PlaceType_MAX = MARKET;
constexpr int PlaceType_ARRAYSIZE = PlaceType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PlaceType_descriptor();
template<typename T>
inline const std::string& PlaceType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PlaceType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PlaceType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PlaceType_descriptor(), enum_t_value);
}
inline bool PlaceType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PlaceType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PlaceType>(
    PlaceType_descriptor(), name, value);
}
enum ShapeType : int {
  NULL_SHAPE_TYPE = 0,
  CIRCLE = 1,
  SQUARE = 2,
  ShapeType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ShapeType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ShapeType_IsValid(int value);
constexpr ShapeType ShapeType_MIN = NULL_SHAPE_TYPE;
constexpr ShapeType ShapeType_MAX = SQUARE;
constexpr int ShapeType_ARRAYSIZE = ShapeType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ShapeType_descriptor();
template<typename T>
inline const std::string& ShapeType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ShapeType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ShapeType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ShapeType_descriptor(), enum_t_value);
}
inline bool ShapeType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ShapeType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ShapeType>(
    ShapeType_descriptor(), name, value);
}
enum PlayerType : int {
  NULL_PLAYER_TYPE = 0,
  CHARACTER = 1,
  TEAM = 2,
  PlayerType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  PlayerType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool PlayerType_IsValid(int value);
constexpr PlayerType PlayerType_MIN = NULL_PLAYER_TYPE;
constexpr PlayerType PlayerType_MAX = TEAM;
constexpr int PlayerType_ARRAYSIZE = PlayerType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PlayerType_descriptor();
template<typename T>
inline const std::string& PlayerType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PlayerType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PlayerType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PlayerType_descriptor(), enum_t_value);
}
inline bool PlayerType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PlayerType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PlayerType>(
    PlayerType_descriptor(), name, value);
}
enum CharacterType : int {
  NULL_CHARACTER_TYPE = 0,
  DRONE = 1,
  ROBOT = 2,
  AUTONOMOUS_CAR = 3,
  CharacterType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  CharacterType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool CharacterType_IsValid(int value);
constexpr CharacterType CharacterType_MIN = NULL_CHARACTER_TYPE;
constexpr CharacterType CharacterType_MAX = AUTONOMOUS_CAR;
constexpr int CharacterType_ARRAYSIZE = CharacterType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CharacterType_descriptor();
template<typename T>
inline const std::string& CharacterType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, CharacterType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function CharacterType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    CharacterType_descriptor(), enum_t_value);
}
inline bool CharacterType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, CharacterType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<CharacterType>(
    CharacterType_descriptor(), name, value);
}
enum CharacterState : int {
  CHARACTER_STATE_NONE = 0,
  CHARACTER_STATE_IDLE = 1,
  CHARACTER_STATE_HARVESTING = 2,
  CHARACTER_STATE_ATTACKING = 3,
  CHARACTER_STATE_OCUPPYING = 4,
  CHARACTER_STATE_TRADING = 5,
  CHARACTER_STATE_MOVING = 6,
  CHARACTER_STATE_KNOCKED_BACK = 7,
  CHARACTER_STATE_DECEASED = 8,
  CharacterState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  CharacterState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool CharacterState_IsValid(int value);
constexpr CharacterState CharacterState_MIN = CHARACTER_STATE_NONE;
constexpr CharacterState CharacterState_MAX = CHARACTER_STATE_DECEASED;
constexpr int CharacterState_ARRAYSIZE = CharacterState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CharacterState_descriptor();
template<typename T>
inline const std::string& CharacterState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, CharacterState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function CharacterState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    CharacterState_descriptor(), enum_t_value);
}
inline bool CharacterState_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, CharacterState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<CharacterState>(
    CharacterState_descriptor(), name, value);
}
enum HomeState : int {
  NULL_HOME_STATE = 0,
  HOME_STATE_IDLE = 1,
  HOME_STATE_PRODUCING_PRODUCT = 2,
  HOME_STATE_REPAIRING = 3,
  HOME_STATE_PRODUCING_CHARACTER = 4,
  HomeState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  HomeState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool HomeState_IsValid(int value);
constexpr HomeState HomeState_MIN = NULL_HOME_STATE;
constexpr HomeState HomeState_MAX = HOME_STATE_PRODUCING_CHARACTER;
constexpr int HomeState_ARRAYSIZE = HomeState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* HomeState_descriptor();
template<typename T>
inline const std::string& HomeState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, HomeState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function HomeState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    HomeState_descriptor(), enum_t_value);
}
inline bool HomeState_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, HomeState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<HomeState>(
    HomeState_descriptor(), name, value);
}
enum ComputeCenterState : int {
  NULL_COMPUTE_CENTER_STATE = 0,
  OCCUPYABLE = 1,
  OCCUPIED = 2,
  ROBBED = 3,
  ComputeCenterState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ComputeCenterState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ComputeCenterState_IsValid(int value);
constexpr ComputeCenterState ComputeCenterState_MIN = NULL_COMPUTE_CENTER_STATE;
constexpr ComputeCenterState ComputeCenterState_MAX = ROBBED;
constexpr int ComputeCenterState_ARRAYSIZE = ComputeCenterState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ComputeCenterState_descriptor();
template<typename T>
inline const std::string& ComputeCenterState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ComputeCenterState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ComputeCenterState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ComputeCenterState_descriptor(), enum_t_value);
}
inline bool ComputeCenterState_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ComputeCenterState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ComputeCenterState>(
    ComputeCenterState_descriptor(), name, value);
}
enum ResourceState : int {
  NULL_ECONOMY_RESOURCE_STSTE = 0,
  HARVESTABLE = 1,
  BEING_HARVESTED = 2,
  HARVESTED = 3,
  ResourceState_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ResourceState_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ResourceState_IsValid(int value);
constexpr ResourceState ResourceState_MIN = NULL_ECONOMY_RESOURCE_STSTE;
constexpr ResourceState ResourceState_MAX = HARVESTED;
constexpr int ResourceState_ARRAYSIZE = ResourceState_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ResourceState_descriptor();
template<typename T>
inline const std::string& ResourceState_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ResourceState>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ResourceState_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ResourceState_descriptor(), enum_t_value);
}
inline bool ResourceState_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ResourceState* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ResourceState>(
    ResourceState_descriptor(), name, value);
}
enum ResourceType : int {
  NULL_RESOURCE_TYPE = 0,
  SMALL_RESOURCE = 1,
  MEDIUM_RESOURCE = 2,
  LARGE_RESOURCE = 3,
  ResourceType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ResourceType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ResourceType_IsValid(int value);
constexpr ResourceType ResourceType_MIN = NULL_RESOURCE_TYPE;
constexpr ResourceType ResourceType_MAX = LARGE_RESOURCE;
constexpr int ResourceType_ARRAYSIZE = ResourceType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ResourceType_descriptor();
template<typename T>
inline const std::string& ResourceType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ResourceType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ResourceType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ResourceType_descriptor(), enum_t_value);
}
inline bool ResourceType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ResourceType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ResourceType>(
    ResourceType_descriptor(), name, value);
}
enum NewsType : int {
  NULL_NEWS_TYPE = 0,
  TEXT = 1,
  BINARY = 2,
  NewsType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  NewsType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool NewsType_IsValid(int value);
constexpr NewsType NewsType_MIN = NULL_NEWS_TYPE;
constexpr NewsType NewsType_MAX = BINARY;
constexpr int NewsType_ARRAYSIZE = NewsType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* NewsType_descriptor();
template<typename T>
inline const std::string& NewsType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, NewsType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function NewsType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    NewsType_descriptor(), enum_t_value);
}
inline bool NewsType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, NewsType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<NewsType>(
    NewsType_descriptor(), name, value);
}
enum GoodsType : int {
  NULL_GOODS_TYPE = 0,
  SEMICONDUCTOR = 1,
  MEDICINE = 2,
  TOYS = 3,
  CLOTHES = 4,
  FOOD = 5,
  GoodsType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  GoodsType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool GoodsType_IsValid(int value);
constexpr GoodsType GoodsType_MIN = NULL_GOODS_TYPE;
constexpr GoodsType GoodsType_MAX = FOOD;
constexpr int GoodsType_ARRAYSIZE = GoodsType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GoodsType_descriptor();
template<typename T>
inline const std::string& GoodsType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, GoodsType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function GoodsType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    GoodsType_descriptor(), enum_t_value);
}
inline bool GoodsType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, GoodsType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<GoodsType>(
    GoodsType_descriptor(), name, value);
}
enum MarketType : int {
  NULL_MARKET_TYPE = 0,
  SMALL_MARKET = 1,
  MEDIUM_MARKET = 2,
  LARGE_MARKET = 3,
  MarketType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MarketType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MarketType_IsValid(int value);
constexpr MarketType MarketType_MIN = NULL_MARKET_TYPE;
constexpr MarketType MarketType_MAX = LARGE_MARKET;
constexpr int MarketType_ARRAYSIZE = MarketType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MarketType_descriptor();
template<typename T>
inline const std::string& MarketType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MarketType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MarketType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MarketType_descriptor(), enum_t_value);
}
inline bool MarketType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MarketType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MarketType>(
    MarketType_descriptor(), name, value);
}
enum TechType : int {
  NULL_TECH_TYPE = 0,
  INCREASE_HP = 1,
  INCREASE_ATTACK_POWER = 2,
  INCREASE_ATTACK_SIZE = 3,
  INCREASE_ROBUST = 4,
  INCREASE_MOVE_SPEED = 5,
  INCREASE_CARRY_CAPACITY = 6,
  INCREASE_EFFICIENCY = 7,
  INCREASE_PRODUCTION = 8,
  INCREASE_STORAGE = 9,
  INCREASE_PRICE = 10,
  DECREASE_COST = 11,
  TechType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  TechType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool TechType_IsValid(int value);
constexpr TechType TechType_MIN = NULL_TECH_TYPE;
constexpr TechType TechType_MAX = DECREASE_COST;
constexpr int TechType_ARRAYSIZE = TechType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TechType_descriptor();
template<typename T>
inline const std::string& TechType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, TechType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function TechType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    TechType_descriptor(), enum_t_value);
}
inline bool TechType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, TechType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<TechType>(
    TechType_descriptor(), name, value);
}
enum AIEventCategory : int {
  NULL_AI_EVENT_CATEGORY = 0,
  ECONOMIC_EVENT = 1,
  WEATHER_EVENT = 2,
  TECHNOLOGY_EVENT = 3,
  COMBAT_EVENT = 4,
  AIEventCategory_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  AIEventCategory_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool AIEventCategory_IsValid(int value);
constexpr AIEventCategory AIEventCategory_MIN = NULL_AI_EVENT_CATEGORY;
constexpr AIEventCategory AIEventCategory_MAX = COMBAT_EVENT;
constexpr int AIEventCategory_ARRAYSIZE = AIEventCategory_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AIEventCategory_descriptor();
template<typename T>
inline const std::string& AIEventCategory_Name(T enum_t_value) {
  static_assert(::std::is_same<T, AIEventCategory>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function AIEventCategory_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    AIEventCategory_descriptor(), enum_t_value);
}
inline bool AIEventCategory_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, AIEventCategory* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<AIEventCategory>(
    AIEventCategory_descriptor(), name, value);
}
enum TaskType : int {
  NULL_TASK_TYPE = 0,
  PRODUCE_PRODUCT = 1,
  HARVEST_RESOURCE = 2,
  OCCUPY_CENTER = 3,
  REPAIR_UNIT = 4,
  TaskType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  TaskType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool TaskType_IsValid(int value);
constexpr TaskType TaskType_MIN = NULL_TASK_TYPE;
constexpr TaskType TaskType_MAX = REPAIR_UNIT;
constexpr int TaskType_ARRAYSIZE = TaskType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TaskType_descriptor();
template<typename T>
inline const std::string& TaskType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, TaskType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function TaskType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    TaskType_descriptor(), enum_t_value);
}
inline bool TaskType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, TaskType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<TaskType>(
    TaskType_descriptor(), name, value);
}
enum AIActionType : int {
  UNKNOWN = 0,
  PRODUCE = 1,
  HARVEST = 2,
  MOVE = 3,
  ATTACK = 4,
  REPAIR = 5,
  SELL = 6,
  OCCUPY = 7,
  AIActionType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  AIActionType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool AIActionType_IsValid(int value);
constexpr AIActionType AIActionType_MIN = UNKNOWN;
constexpr AIActionType AIActionType_MAX = OCCUPY;
constexpr int AIActionType_ARRAYSIZE = AIActionType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AIActionType_descriptor();
template<typename T>
inline const std::string& AIActionType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, AIActionType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function AIActionType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    AIActionType_descriptor(), enum_t_value);
}
inline bool AIActionType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, AIActionType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<AIActionType>(
    AIActionType_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::protobuf::GameMode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf::GameMode>() {
  return ::protobuf::GameMode_descriptor();
}
template <> struct is_proto_enum< ::protobuf::GameState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf::GameState>() {
  return ::protobuf::GameState_descriptor();
}
template <> struct is_proto_enum< ::protobuf::PlaceType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf::PlaceType>() {
  return ::protobuf::PlaceType_descriptor();
}
template <> struct is_proto_enum< ::protobuf::ShapeType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf::ShapeType>() {
  return ::protobuf::ShapeType_descriptor();
}
template <> struct is_proto_enum< ::protobuf::PlayerType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf::PlayerType>() {
  return ::protobuf::PlayerType_descriptor();
}
template <> struct is_proto_enum< ::protobuf::CharacterType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf::CharacterType>() {
  return ::protobuf::CharacterType_descriptor();
}
template <> struct is_proto_enum< ::protobuf::CharacterState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf::CharacterState>() {
  return ::protobuf::CharacterState_descriptor();
}
template <> struct is_proto_enum< ::protobuf::HomeState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf::HomeState>() {
  return ::protobuf::HomeState_descriptor();
}
template <> struct is_proto_enum< ::protobuf::ComputeCenterState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf::ComputeCenterState>() {
  return ::protobuf::ComputeCenterState_descriptor();
}
template <> struct is_proto_enum< ::protobuf::ResourceState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf::ResourceState>() {
  return ::protobuf::ResourceState_descriptor();
}
template <> struct is_proto_enum< ::protobuf::ResourceType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf::ResourceType>() {
  return ::protobuf::ResourceType_descriptor();
}
template <> struct is_proto_enum< ::protobuf::NewsType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf::NewsType>() {
  return ::protobuf::NewsType_descriptor();
}
template <> struct is_proto_enum< ::protobuf::GoodsType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf::GoodsType>() {
  return ::protobuf::GoodsType_descriptor();
}
template <> struct is_proto_enum< ::protobuf::MarketType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf::MarketType>() {
  return ::protobuf::MarketType_descriptor();
}
template <> struct is_proto_enum< ::protobuf::TechType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf::TechType>() {
  return ::protobuf::TechType_descriptor();
}
template <> struct is_proto_enum< ::protobuf::AIEventCategory> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf::AIEventCategory>() {
  return ::protobuf::AIEventCategory_descriptor();
}
template <> struct is_proto_enum< ::protobuf::TaskType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf::TaskType>() {
  return ::protobuf::TaskType_descriptor();
}
template <> struct is_proto_enum< ::protobuf::AIActionType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::protobuf::AIActionType>() {
  return ::protobuf::AIActionType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_MessageType_2eproto
