// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MessageType.proto
// Protobuf C++ Version: 6.33.4

#include "MessageType.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protobuf {
}  // namespace protobuf
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_MessageType_2eproto[18];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_MessageType_2eproto = nullptr;
const ::uint32_t TableStruct_MessageType_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* PROTOBUF_NULLABLE schemas = nullptr;
static constexpr ::_pb::Message* PROTOBUF_NONNULL const* PROTOBUF_NULLABLE
    file_default_instances = nullptr;
const char descriptor_table_protodef_MessageType_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021MessageType.proto\022\010protobuf*D\n\010GameMod"
    "e\022\022\n\016NULL_GAME_MODE\020\000\022\021\n\rGAME_MODE_PVE\020\001"
    "\022\021\n\rGAME_MODE_PVP\020\002*P\n\tGameState\022\023\n\017NULL"
    "_GAME_STATE\020\000\022\016\n\nGAME_START\020\001\022\020\n\014GAME_RU"
    "NNING\020\002\022\014\n\010GAME_END\020\003*}\n\tPlaceType\022\023\n\017NU"
    "LL_PLACE_TYPE\020\000\022\013\n\007FACTORY\020\001\022\t\n\005SPACE\020\002\022"
    "\013\n\007BARRIER\020\003\022\010\n\004BUSH\020\004\022\014\n\010RESOURCE\020\005\022\022\n\016"
    "COMPUTE_CENTER\020\006\022\n\n\006MARKET\020\007*8\n\tShapeTyp"
    "e\022\023\n\017NULL_SHAPE_TYPE\020\000\022\n\n\006CIRCLE\020\001\022\n\n\006SQ"
    "UARE\020\002*;\n\nPlayerType\022\024\n\020NULL_PLAYER_TYPE"
    "\020\000\022\r\n\tCHARACTER\020\001\022\010\n\004TEAM\020\002*R\n\rCharacter"
    "Type\022\027\n\023NULL_CHARACTER_TYPE\020\000\022\t\n\005DRONE\020\001"
    "\022\t\n\005ROBOT\020\002\022\022\n\016AUTONOMOUS_CAR\020\003*\233\002\n\016Char"
    "acterState\022\030\n\024CHARACTER_STATE_NONE\020\000\022\030\n\024"
    "CHARACTER_STATE_IDLE\020\001\022\036\n\032CHARACTER_STAT"
    "E_HARVESTING\020\002\022\035\n\031CHARACTER_STATE_ATTACK"
    "ING\020\003\022\035\n\031CHARACTER_STATE_OCUPPYING\020\004\022\033\n\027"
    "CHARACTER_STATE_TRADING\020\005\022\032\n\026CHARACTER_S"
    "TATE_MOVING\020\006\022 \n\034CHARACTER_STATE_KNOCKED"
    "_BACK\020\007\022\034\n\030CHARACTER_STATE_DECEASED\020\010*\225\001"
    "\n\tHomeState\022\023\n\017NULL_HOME_STATE\020\000\022\023\n\017HOME"
    "_STATE_IDLE\020\001\022 \n\034HOME_STATE_PRODUCING_PR"
    "ODUCT\020\002\022\030\n\024HOME_STATE_REPAIRING\020\003\022\"\n\036HOM"
    "E_STATE_PRODUCING_CHARACTER\020\004*]\n\022Compute"
    "CenterState\022\035\n\031NULL_COMPUTE_CENTER_STATE"
    "\020\000\022\016\n\nOCCUPYABLE\020\001\022\014\n\010OCCUPIED\020\002\022\n\n\006ROBB"
    "ED\020\003*e\n\rResourceState\022\037\n\033NULL_ECONOMY_RE"
    "SOURCE_STSTE\020\000\022\017\n\013HARVESTABLE\020\001\022\023\n\017BEING"
    "_HARVESTED\020\002\022\r\n\tHARVESTED\020\003*c\n\014ResourceT"
    "ype\022\026\n\022NULL_RESOURCE_TYPE\020\000\022\022\n\016SMALL_RES"
    "OURCE\020\001\022\023\n\017MEDIUM_RESOURCE\020\002\022\022\n\016LARGE_RE"
    "SOURCE\020\003*4\n\010NewsType\022\022\n\016NULL_NEWS_TYPE\020\000"
    "\022\010\n\004TEXT\020\001\022\n\n\006BINARY\020\002*b\n\tGoodsType\022\023\n\017N"
    "ULL_GOODS_TYPE\020\000\022\021\n\rSEMICONDUCTOR\020\001\022\014\n\010M"
    "EDICINE\020\002\022\010\n\004TOYS\020\003\022\013\n\007CLOTHES\020\004\022\010\n\004FOOD"
    "\020\005*Y\n\nMarketType\022\024\n\020NULL_MARKET_TYPE\020\000\022\020"
    "\n\014SMALL_MARKET\020\001\022\021\n\rMEDIUM_MARKET\020\002\022\020\n\014L"
    "ARGE_MARKET\020\003*\236\002\n\010TechType\022\022\n\016NULL_TECH_"
    "TYPE\020\000\022\017\n\013INCREASE_HP\020\001\022\031\n\025INCREASE_ATTA"
    "CK_POWER\020\002\022\030\n\024INCREASE_ATTACK_SIZE\020\003\022\023\n\017"
    "INCREASE_ROBUST\020\004\022\027\n\023INCREASE_MOVE_SPEED"
    "\020\005\022\033\n\027INCREASE_CARRY_CAPACITY\020\006\022\027\n\023INCRE"
    "ASE_EFFICIENCY\020\007\022\027\n\023INCREASE_PRODUCTION\020"
    "\010\022\024\n\020INCREASE_STORAGE\020\t\022\022\n\016INCREASE_PRIC"
    "E\020\n\022\021\n\rDECREASE_COST\020\013*|\n\017AIEventCategor"
    "y\022\032\n\026NULL_AI_EVENT_CATEGORY\020\000\022\022\n\016ECONOMI"
    "C_EVENT\020\001\022\021\n\rWEATHER_EVENT\020\002\022\024\n\020TECHNOLO"
    "GY_EVENT\020\003\022\020\n\014COMBAT_EVENT\020\004*m\n\010TaskType"
    "\022\022\n\016NULL_TASK_TYPE\020\000\022\023\n\017PRODUCE_PRODUCT\020"
    "\001\022\024\n\020HARVEST_RESOURCE\020\002\022\021\n\rOCCUPY_CENTER"
    "\020\003\022\017\n\013REPAIR_UNIT\020\004*m\n\014AIActionType\022\013\n\007U"
    "NKNOWN\020\000\022\013\n\007PRODUCE\020\001\022\013\n\007HARVEST\020\002\022\010\n\004MO"
    "VE\020\003\022\n\n\006ATTACK\020\004\022\n\n\006REPAIR\020\005\022\010\n\004SELL\020\006\022\n"
    "\n\006OCCUPY\020\007b\006proto3"
};
static ::absl::once_flag descriptor_table_MessageType_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_MessageType_2eproto = {
    false,
    false,
    2138,
    descriptor_table_protodef_MessageType_2eproto,
    "MessageType.proto",
    &descriptor_table_MessageType_2eproto_once,
    nullptr,
    0,
    0,
    schemas,
    file_default_instances,
    TableStruct_MessageType_2eproto::offsets,
    file_level_enum_descriptors_MessageType_2eproto,
    file_level_service_descriptors_MessageType_2eproto,
};
namespace protobuf {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL GameMode_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t GameMode_internal_data_[] = {
    196608u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL GameState_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t GameState_internal_data_[] = {
    262144u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL PlaceType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t PlaceType_internal_data_[] = {
    524288u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ShapeType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[3];
}
PROTOBUF_CONSTINIT const uint32_t ShapeType_internal_data_[] = {
    196608u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL PlayerType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[4];
}
PROTOBUF_CONSTINIT const uint32_t PlayerType_internal_data_[] = {
    196608u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL CharacterType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[5];
}
PROTOBUF_CONSTINIT const uint32_t CharacterType_internal_data_[] = {
    262144u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL CharacterState_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[6];
}
PROTOBUF_CONSTINIT const uint32_t CharacterState_internal_data_[] = {
    589824u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL HomeState_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[7];
}
PROTOBUF_CONSTINIT const uint32_t HomeState_internal_data_[] = {
    327680u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ComputeCenterState_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[8];
}
PROTOBUF_CONSTINIT const uint32_t ComputeCenterState_internal_data_[] = {
    262144u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ResourceState_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[9];
}
PROTOBUF_CONSTINIT const uint32_t ResourceState_internal_data_[] = {
    262144u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ResourceType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[10];
}
PROTOBUF_CONSTINIT const uint32_t ResourceType_internal_data_[] = {
    262144u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL NewsType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[11];
}
PROTOBUF_CONSTINIT const uint32_t NewsType_internal_data_[] = {
    196608u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL GoodsType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[12];
}
PROTOBUF_CONSTINIT const uint32_t GoodsType_internal_data_[] = {
    393216u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL MarketType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[13];
}
PROTOBUF_CONSTINIT const uint32_t MarketType_internal_data_[] = {
    262144u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL TechType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[14];
}
PROTOBUF_CONSTINIT const uint32_t TechType_internal_data_[] = {
    786432u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL AIEventCategory_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[15];
}
PROTOBUF_CONSTINIT const uint32_t AIEventCategory_internal_data_[] = {
    327680u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL TaskType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[16];
}
PROTOBUF_CONSTINIT const uint32_t TaskType_internal_data_[] = {
    327680u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL AIActionType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[17];
}
PROTOBUF_CONSTINIT const uint32_t AIActionType_internal_data_[] = {
    524288u, 0u, };
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_MessageType_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
