// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MessageType.proto
// Protobuf C++ Version: 6.33.4

#ifndef MessageType_2eproto_2epb_2eh
#define MessageType_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_MessageType_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_MessageType_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_MessageType_2eproto;
}  // extern "C"
namespace protobuf {
enum AIActionType : int;
extern const uint32_t AIActionType_internal_data_[];
enum AIEventCategory : int;
extern const uint32_t AIEventCategory_internal_data_[];
enum CharacterState : int;
extern const uint32_t CharacterState_internal_data_[];
enum CharacterType : int;
extern const uint32_t CharacterType_internal_data_[];
enum ComputeCenterState : int;
extern const uint32_t ComputeCenterState_internal_data_[];
enum GameMode : int;
extern const uint32_t GameMode_internal_data_[];
enum GameState : int;
extern const uint32_t GameState_internal_data_[];
enum GoodsType : int;
extern const uint32_t GoodsType_internal_data_[];
enum HomeState : int;
extern const uint32_t HomeState_internal_data_[];
enum MarketType : int;
extern const uint32_t MarketType_internal_data_[];
enum NewsType : int;
extern const uint32_t NewsType_internal_data_[];
enum PlaceType : int;
extern const uint32_t PlaceType_internal_data_[];
enum PlayerType : int;
extern const uint32_t PlayerType_internal_data_[];
enum ResourceState : int;
extern const uint32_t ResourceState_internal_data_[];
enum ResourceType : int;
extern const uint32_t ResourceType_internal_data_[];
enum ShapeType : int;
extern const uint32_t ShapeType_internal_data_[];
enum TaskType : int;
extern const uint32_t TaskType_internal_data_[];
enum TechType : int;
extern const uint32_t TechType_internal_data_[];
}  // namespace protobuf
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::protobuf::AIActionType_internal_data_>
    internal::EnumTraitsImpl::value<::protobuf::AIActionType>;
template <>
internal::EnumTraitsT<::protobuf::AIEventCategory_internal_data_>
    internal::EnumTraitsImpl::value<::protobuf::AIEventCategory>;
template <>
internal::EnumTraitsT<::protobuf::CharacterState_internal_data_>
    internal::EnumTraitsImpl::value<::protobuf::CharacterState>;
template <>
internal::EnumTraitsT<::protobuf::CharacterType_internal_data_>
    internal::EnumTraitsImpl::value<::protobuf::CharacterType>;
template <>
internal::EnumTraitsT<::protobuf::ComputeCenterState_internal_data_>
    internal::EnumTraitsImpl::value<::protobuf::ComputeCenterState>;
template <>
internal::EnumTraitsT<::protobuf::GameMode_internal_data_>
    internal::EnumTraitsImpl::value<::protobuf::GameMode>;
template <>
internal::EnumTraitsT<::protobuf::GameState_internal_data_>
    internal::EnumTraitsImpl::value<::protobuf::GameState>;
template <>
internal::EnumTraitsT<::protobuf::GoodsType_internal_data_>
    internal::EnumTraitsImpl::value<::protobuf::GoodsType>;
template <>
internal::EnumTraitsT<::protobuf::HomeState_internal_data_>
    internal::EnumTraitsImpl::value<::protobuf::HomeState>;
template <>
internal::EnumTraitsT<::protobuf::MarketType_internal_data_>
    internal::EnumTraitsImpl::value<::protobuf::MarketType>;
template <>
internal::EnumTraitsT<::protobuf::NewsType_internal_data_>
    internal::EnumTraitsImpl::value<::protobuf::NewsType>;
template <>
internal::EnumTraitsT<::protobuf::PlaceType_internal_data_>
    internal::EnumTraitsImpl::value<::protobuf::PlaceType>;
template <>
internal::EnumTraitsT<::protobuf::PlayerType_internal_data_>
    internal::EnumTraitsImpl::value<::protobuf::PlayerType>;
template <>
internal::EnumTraitsT<::protobuf::ResourceState_internal_data_>
    internal::EnumTraitsImpl::value<::protobuf::ResourceState>;
template <>
internal::EnumTraitsT<::protobuf::ResourceType_internal_data_>
    internal::EnumTraitsImpl::value<::protobuf::ResourceType>;
template <>
internal::EnumTraitsT<::protobuf::ShapeType_internal_data_>
    internal::EnumTraitsImpl::value<::protobuf::ShapeType>;
template <>
internal::EnumTraitsT<::protobuf::TaskType_internal_data_>
    internal::EnumTraitsImpl::value<::protobuf::TaskType>;
template <>
internal::EnumTraitsT<::protobuf::TechType_internal_data_>
    internal::EnumTraitsImpl::value<::protobuf::TechType>;
}  // namespace protobuf
}  // namespace google

namespace protobuf {
enum GameMode : int {
  NULL_GAME_MODE = 0,
  GAME_MODE_PVE = 1,
  GAME_MODE_PVP = 2,
  GameMode_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  GameMode_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t GameMode_internal_data_[];
inline constexpr GameMode GameMode_MIN =
    static_cast<GameMode>(0);
inline constexpr GameMode GameMode_MAX =
    static_cast<GameMode>(2);
inline bool GameMode_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int GameMode_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL GameMode_descriptor();
template <typename T>
const ::std::string& GameMode_Name(T value) {
  static_assert(::std::is_same<T, GameMode>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to GameMode_Name().");
  return GameMode_Name(static_cast<GameMode>(value));
}
template <>
inline const ::std::string& GameMode_Name(GameMode value) {
  return ::google::protobuf::internal::NameOfDenseEnum<GameMode_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool GameMode_Parse(
    ::absl::string_view name, GameMode* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<GameMode>(GameMode_descriptor(), name,
                                           value);
}
enum GameState : int {
  NULL_GAME_STATE = 0,
  GAME_START = 1,
  GAME_RUNNING = 2,
  GAME_END = 3,
  GameState_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  GameState_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t GameState_internal_data_[];
inline constexpr GameState GameState_MIN =
    static_cast<GameState>(0);
inline constexpr GameState GameState_MAX =
    static_cast<GameState>(3);
inline bool GameState_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int GameState_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL GameState_descriptor();
template <typename T>
const ::std::string& GameState_Name(T value) {
  static_assert(::std::is_same<T, GameState>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to GameState_Name().");
  return GameState_Name(static_cast<GameState>(value));
}
template <>
inline const ::std::string& GameState_Name(GameState value) {
  return ::google::protobuf::internal::NameOfDenseEnum<GameState_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool GameState_Parse(
    ::absl::string_view name, GameState* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<GameState>(GameState_descriptor(), name,
                                           value);
}
enum PlaceType : int {
  NULL_PLACE_TYPE = 0,
  FACTORY = 1,
  SPACE = 2,
  BARRIER = 3,
  BUSH = 4,
  RESOURCE = 5,
  COMPUTE_CENTER = 6,
  MARKET = 7,
  PlaceType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  PlaceType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t PlaceType_internal_data_[];
inline constexpr PlaceType PlaceType_MIN =
    static_cast<PlaceType>(0);
inline constexpr PlaceType PlaceType_MAX =
    static_cast<PlaceType>(7);
inline bool PlaceType_IsValid(int value) {
  return 0 <= value && value <= 7;
}
inline constexpr int PlaceType_ARRAYSIZE = 7 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL PlaceType_descriptor();
template <typename T>
const ::std::string& PlaceType_Name(T value) {
  static_assert(::std::is_same<T, PlaceType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to PlaceType_Name().");
  return PlaceType_Name(static_cast<PlaceType>(value));
}
template <>
inline const ::std::string& PlaceType_Name(PlaceType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<PlaceType_descriptor, 0, 7>(
      static_cast<int>(value));
}
inline bool PlaceType_Parse(
    ::absl::string_view name, PlaceType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<PlaceType>(PlaceType_descriptor(), name,
                                           value);
}
enum ShapeType : int {
  NULL_SHAPE_TYPE = 0,
  CIRCLE = 1,
  SQUARE = 2,
  ShapeType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  ShapeType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t ShapeType_internal_data_[];
inline constexpr ShapeType ShapeType_MIN =
    static_cast<ShapeType>(0);
inline constexpr ShapeType ShapeType_MAX =
    static_cast<ShapeType>(2);
inline bool ShapeType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int ShapeType_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ShapeType_descriptor();
template <typename T>
const ::std::string& ShapeType_Name(T value) {
  static_assert(::std::is_same<T, ShapeType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ShapeType_Name().");
  return ShapeType_Name(static_cast<ShapeType>(value));
}
template <>
inline const ::std::string& ShapeType_Name(ShapeType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ShapeType_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool ShapeType_Parse(
    ::absl::string_view name, ShapeType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<ShapeType>(ShapeType_descriptor(), name,
                                           value);
}
enum PlayerType : int {
  NULL_PLAYER_TYPE = 0,
  CHARACTER = 1,
  TEAM = 2,
  PlayerType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  PlayerType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t PlayerType_internal_data_[];
inline constexpr PlayerType PlayerType_MIN =
    static_cast<PlayerType>(0);
inline constexpr PlayerType PlayerType_MAX =
    static_cast<PlayerType>(2);
inline bool PlayerType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int PlayerType_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL PlayerType_descriptor();
template <typename T>
const ::std::string& PlayerType_Name(T value) {
  static_assert(::std::is_same<T, PlayerType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to PlayerType_Name().");
  return PlayerType_Name(static_cast<PlayerType>(value));
}
template <>
inline const ::std::string& PlayerType_Name(PlayerType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<PlayerType_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool PlayerType_Parse(
    ::absl::string_view name, PlayerType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<PlayerType>(PlayerType_descriptor(), name,
                                           value);
}
enum CharacterType : int {
  NULL_CHARACTER_TYPE = 0,
  DRONE = 1,
  ROBOT = 2,
  AUTONOMOUS_CAR = 3,
  CharacterType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  CharacterType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t CharacterType_internal_data_[];
inline constexpr CharacterType CharacterType_MIN =
    static_cast<CharacterType>(0);
inline constexpr CharacterType CharacterType_MAX =
    static_cast<CharacterType>(3);
inline bool CharacterType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int CharacterType_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL CharacterType_descriptor();
template <typename T>
const ::std::string& CharacterType_Name(T value) {
  static_assert(::std::is_same<T, CharacterType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to CharacterType_Name().");
  return CharacterType_Name(static_cast<CharacterType>(value));
}
template <>
inline const ::std::string& CharacterType_Name(CharacterType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<CharacterType_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool CharacterType_Parse(
    ::absl::string_view name, CharacterType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<CharacterType>(CharacterType_descriptor(), name,
                                           value);
}
enum CharacterState : int {
  CHARACTER_STATE_NONE = 0,
  CHARACTER_STATE_IDLE = 1,
  CHARACTER_STATE_HARVESTING = 2,
  CHARACTER_STATE_ATTACKING = 3,
  CHARACTER_STATE_OCUPPYING = 4,
  CHARACTER_STATE_TRADING = 5,
  CHARACTER_STATE_MOVING = 6,
  CHARACTER_STATE_KNOCKED_BACK = 7,
  CHARACTER_STATE_DECEASED = 8,
  CharacterState_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  CharacterState_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t CharacterState_internal_data_[];
inline constexpr CharacterState CharacterState_MIN =
    static_cast<CharacterState>(0);
inline constexpr CharacterState CharacterState_MAX =
    static_cast<CharacterState>(8);
inline bool CharacterState_IsValid(int value) {
  return 0 <= value && value <= 8;
}
inline constexpr int CharacterState_ARRAYSIZE = 8 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL CharacterState_descriptor();
template <typename T>
const ::std::string& CharacterState_Name(T value) {
  static_assert(::std::is_same<T, CharacterState>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to CharacterState_Name().");
  return CharacterState_Name(static_cast<CharacterState>(value));
}
template <>
inline const ::std::string& CharacterState_Name(CharacterState value) {
  return ::google::protobuf::internal::NameOfDenseEnum<CharacterState_descriptor, 0, 8>(
      static_cast<int>(value));
}
inline bool CharacterState_Parse(
    ::absl::string_view name, CharacterState* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<CharacterState>(CharacterState_descriptor(), name,
                                           value);
}
enum HomeState : int {
  NULL_HOME_STATE = 0,
  HOME_STATE_IDLE = 1,
  HOME_STATE_PRODUCING_PRODUCT = 2,
  HOME_STATE_REPAIRING = 3,
  HOME_STATE_PRODUCING_CHARACTER = 4,
  HomeState_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  HomeState_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t HomeState_internal_data_[];
inline constexpr HomeState HomeState_MIN =
    static_cast<HomeState>(0);
inline constexpr HomeState HomeState_MAX =
    static_cast<HomeState>(4);
inline bool HomeState_IsValid(int value) {
  return 0 <= value && value <= 4;
}
inline constexpr int HomeState_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL HomeState_descriptor();
template <typename T>
const ::std::string& HomeState_Name(T value) {
  static_assert(::std::is_same<T, HomeState>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to HomeState_Name().");
  return HomeState_Name(static_cast<HomeState>(value));
}
template <>
inline const ::std::string& HomeState_Name(HomeState value) {
  return ::google::protobuf::internal::NameOfDenseEnum<HomeState_descriptor, 0, 4>(
      static_cast<int>(value));
}
inline bool HomeState_Parse(
    ::absl::string_view name, HomeState* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<HomeState>(HomeState_descriptor(), name,
                                           value);
}
enum ComputeCenterState : int {
  NULL_COMPUTE_CENTER_STATE = 0,
  OCCUPYABLE = 1,
  OCCUPIED = 2,
  ROBBED = 3,
  ComputeCenterState_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  ComputeCenterState_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t ComputeCenterState_internal_data_[];
inline constexpr ComputeCenterState ComputeCenterState_MIN =
    static_cast<ComputeCenterState>(0);
inline constexpr ComputeCenterState ComputeCenterState_MAX =
    static_cast<ComputeCenterState>(3);
inline bool ComputeCenterState_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int ComputeCenterState_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ComputeCenterState_descriptor();
template <typename T>
const ::std::string& ComputeCenterState_Name(T value) {
  static_assert(::std::is_same<T, ComputeCenterState>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ComputeCenterState_Name().");
  return ComputeCenterState_Name(static_cast<ComputeCenterState>(value));
}
template <>
inline const ::std::string& ComputeCenterState_Name(ComputeCenterState value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ComputeCenterState_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool ComputeCenterState_Parse(
    ::absl::string_view name, ComputeCenterState* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<ComputeCenterState>(ComputeCenterState_descriptor(), name,
                                           value);
}
enum ResourceState : int {
  NULL_ECONOMY_RESOURCE_STSTE = 0,
  HARVESTABLE = 1,
  BEING_HARVESTED = 2,
  HARVESTED = 3,
  ResourceState_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  ResourceState_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t ResourceState_internal_data_[];
inline constexpr ResourceState ResourceState_MIN =
    static_cast<ResourceState>(0);
inline constexpr ResourceState ResourceState_MAX =
    static_cast<ResourceState>(3);
inline bool ResourceState_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int ResourceState_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ResourceState_descriptor();
template <typename T>
const ::std::string& ResourceState_Name(T value) {
  static_assert(::std::is_same<T, ResourceState>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ResourceState_Name().");
  return ResourceState_Name(static_cast<ResourceState>(value));
}
template <>
inline const ::std::string& ResourceState_Name(ResourceState value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ResourceState_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool ResourceState_Parse(
    ::absl::string_view name, ResourceState* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<ResourceState>(ResourceState_descriptor(), name,
                                           value);
}
enum ResourceType : int {
  NULL_RESOURCE_TYPE = 0,
  SMALL_RESOURCE = 1,
  MEDIUM_RESOURCE = 2,
  LARGE_RESOURCE = 3,
  ResourceType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  ResourceType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t ResourceType_internal_data_[];
inline constexpr ResourceType ResourceType_MIN =
    static_cast<ResourceType>(0);
inline constexpr ResourceType ResourceType_MAX =
    static_cast<ResourceType>(3);
inline bool ResourceType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int ResourceType_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ResourceType_descriptor();
template <typename T>
const ::std::string& ResourceType_Name(T value) {
  static_assert(::std::is_same<T, ResourceType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ResourceType_Name().");
  return ResourceType_Name(static_cast<ResourceType>(value));
}
template <>
inline const ::std::string& ResourceType_Name(ResourceType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ResourceType_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool ResourceType_Parse(
    ::absl::string_view name, ResourceType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<ResourceType>(ResourceType_descriptor(), name,
                                           value);
}
enum NewsType : int {
  NULL_NEWS_TYPE = 0,
  TEXT = 1,
  BINARY = 2,
  NewsType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  NewsType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t NewsType_internal_data_[];
inline constexpr NewsType NewsType_MIN =
    static_cast<NewsType>(0);
inline constexpr NewsType NewsType_MAX =
    static_cast<NewsType>(2);
inline bool NewsType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int NewsType_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL NewsType_descriptor();
template <typename T>
const ::std::string& NewsType_Name(T value) {
  static_assert(::std::is_same<T, NewsType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to NewsType_Name().");
  return NewsType_Name(static_cast<NewsType>(value));
}
template <>
inline const ::std::string& NewsType_Name(NewsType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<NewsType_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool NewsType_Parse(
    ::absl::string_view name, NewsType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<NewsType>(NewsType_descriptor(), name,
                                           value);
}
enum GoodsType : int {
  NULL_GOODS_TYPE = 0,
  SEMICONDUCTOR = 1,
  MEDICINE = 2,
  TOYS = 3,
  CLOTHES = 4,
  FOOD = 5,
  GoodsType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  GoodsType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t GoodsType_internal_data_[];
inline constexpr GoodsType GoodsType_MIN =
    static_cast<GoodsType>(0);
inline constexpr GoodsType GoodsType_MAX =
    static_cast<GoodsType>(5);
inline bool GoodsType_IsValid(int value) {
  return 0 <= value && value <= 5;
}
inline constexpr int GoodsType_ARRAYSIZE = 5 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL GoodsType_descriptor();
template <typename T>
const ::std::string& GoodsType_Name(T value) {
  static_assert(::std::is_same<T, GoodsType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to GoodsType_Name().");
  return GoodsType_Name(static_cast<GoodsType>(value));
}
template <>
inline const ::std::string& GoodsType_Name(GoodsType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<GoodsType_descriptor, 0, 5>(
      static_cast<int>(value));
}
inline bool GoodsType_Parse(
    ::absl::string_view name, GoodsType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<GoodsType>(GoodsType_descriptor(), name,
                                           value);
}
enum MarketType : int {
  NULL_MARKET_TYPE = 0,
  SMALL_MARKET = 1,
  MEDIUM_MARKET = 2,
  LARGE_MARKET = 3,
  MarketType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  MarketType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t MarketType_internal_data_[];
inline constexpr MarketType MarketType_MIN =
    static_cast<MarketType>(0);
inline constexpr MarketType MarketType_MAX =
    static_cast<MarketType>(3);
inline bool MarketType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int MarketType_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL MarketType_descriptor();
template <typename T>
const ::std::string& MarketType_Name(T value) {
  static_assert(::std::is_same<T, MarketType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to MarketType_Name().");
  return MarketType_Name(static_cast<MarketType>(value));
}
template <>
inline const ::std::string& MarketType_Name(MarketType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<MarketType_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool MarketType_Parse(
    ::absl::string_view name, MarketType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<MarketType>(MarketType_descriptor(), name,
                                           value);
}
enum TechType : int {
  NULL_TECH_TYPE = 0,
  INCREASE_HP = 1,
  INCREASE_ATTACK_POWER = 2,
  INCREASE_ATTACK_SIZE = 3,
  INCREASE_ROBUST = 4,
  INCREASE_MOVE_SPEED = 5,
  INCREASE_CARRY_CAPACITY = 6,
  INCREASE_EFFICIENCY = 7,
  INCREASE_PRODUCTION = 8,
  INCREASE_STORAGE = 9,
  INCREASE_PRICE = 10,
  DECREASE_COST = 11,
  TechType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  TechType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t TechType_internal_data_[];
inline constexpr TechType TechType_MIN =
    static_cast<TechType>(0);
inline constexpr TechType TechType_MAX =
    static_cast<TechType>(11);
inline bool TechType_IsValid(int value) {
  return 0 <= value && value <= 11;
}
inline constexpr int TechType_ARRAYSIZE = 11 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL TechType_descriptor();
template <typename T>
const ::std::string& TechType_Name(T value) {
  static_assert(::std::is_same<T, TechType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to TechType_Name().");
  return TechType_Name(static_cast<TechType>(value));
}
template <>
inline const ::std::string& TechType_Name(TechType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<TechType_descriptor, 0, 11>(
      static_cast<int>(value));
}
inline bool TechType_Parse(
    ::absl::string_view name, TechType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<TechType>(TechType_descriptor(), name,
                                           value);
}
enum AIEventCategory : int {
  NULL_AI_EVENT_CATEGORY = 0,
  ECONOMIC_EVENT = 1,
  WEATHER_EVENT = 2,
  TECHNOLOGY_EVENT = 3,
  COMBAT_EVENT = 4,
  AIEventCategory_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  AIEventCategory_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t AIEventCategory_internal_data_[];
inline constexpr AIEventCategory AIEventCategory_MIN =
    static_cast<AIEventCategory>(0);
inline constexpr AIEventCategory AIEventCategory_MAX =
    static_cast<AIEventCategory>(4);
inline bool AIEventCategory_IsValid(int value) {
  return 0 <= value && value <= 4;
}
inline constexpr int AIEventCategory_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL AIEventCategory_descriptor();
template <typename T>
const ::std::string& AIEventCategory_Name(T value) {
  static_assert(::std::is_same<T, AIEventCategory>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to AIEventCategory_Name().");
  return AIEventCategory_Name(static_cast<AIEventCategory>(value));
}
template <>
inline const ::std::string& AIEventCategory_Name(AIEventCategory value) {
  return ::google::protobuf::internal::NameOfDenseEnum<AIEventCategory_descriptor, 0, 4>(
      static_cast<int>(value));
}
inline bool AIEventCategory_Parse(
    ::absl::string_view name, AIEventCategory* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<AIEventCategory>(AIEventCategory_descriptor(), name,
                                           value);
}
enum TaskType : int {
  NULL_TASK_TYPE = 0,
  PRODUCE_PRODUCT = 1,
  HARVEST_RESOURCE = 2,
  OCCUPY_CENTER = 3,
  REPAIR_UNIT = 4,
  TaskType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  TaskType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t TaskType_internal_data_[];
inline constexpr TaskType TaskType_MIN =
    static_cast<TaskType>(0);
inline constexpr TaskType TaskType_MAX =
    static_cast<TaskType>(4);
inline bool TaskType_IsValid(int value) {
  return 0 <= value && value <= 4;
}
inline constexpr int TaskType_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL TaskType_descriptor();
template <typename T>
const ::std::string& TaskType_Name(T value) {
  static_assert(::std::is_same<T, TaskType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to TaskType_Name().");
  return TaskType_Name(static_cast<TaskType>(value));
}
template <>
inline const ::std::string& TaskType_Name(TaskType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<TaskType_descriptor, 0, 4>(
      static_cast<int>(value));
}
inline bool TaskType_Parse(
    ::absl::string_view name, TaskType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<TaskType>(TaskType_descriptor(), name,
                                           value);
}
enum AIActionType : int {
  UNKNOWN = 0,
  PRODUCE = 1,
  HARVEST = 2,
  MOVE = 3,
  ATTACK = 4,
  REPAIR = 5,
  SELL = 6,
  OCCUPY = 7,
  AIActionType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  AIActionType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t AIActionType_internal_data_[];
inline constexpr AIActionType AIActionType_MIN =
    static_cast<AIActionType>(0);
inline constexpr AIActionType AIActionType_MAX =
    static_cast<AIActionType>(7);
inline bool AIActionType_IsValid(int value) {
  return 0 <= value && value <= 7;
}
inline constexpr int AIActionType_ARRAYSIZE = 7 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL AIActionType_descriptor();
template <typename T>
const ::std::string& AIActionType_Name(T value) {
  static_assert(::std::is_same<T, AIActionType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to AIActionType_Name().");
  return AIActionType_Name(static_cast<AIActionType>(value));
}
template <>
inline const ::std::string& AIActionType_Name(AIActionType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<AIActionType_descriptor, 0, 7>(
      static_cast<int>(value));
}
inline bool AIActionType_Parse(
    ::absl::string_view name, AIActionType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<AIActionType>(AIActionType_descriptor(), name,
                                           value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::protobuf::GameMode> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::protobuf::GameMode>() {
  return ::protobuf::GameMode_descriptor();
}
template <>
struct is_proto_enum<::protobuf::GameState> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::protobuf::GameState>() {
  return ::protobuf::GameState_descriptor();
}
template <>
struct is_proto_enum<::protobuf::PlaceType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::protobuf::PlaceType>() {
  return ::protobuf::PlaceType_descriptor();
}
template <>
struct is_proto_enum<::protobuf::ShapeType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::protobuf::ShapeType>() {
  return ::protobuf::ShapeType_descriptor();
}
template <>
struct is_proto_enum<::protobuf::PlayerType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::protobuf::PlayerType>() {
  return ::protobuf::PlayerType_descriptor();
}
template <>
struct is_proto_enum<::protobuf::CharacterType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::protobuf::CharacterType>() {
  return ::protobuf::CharacterType_descriptor();
}
template <>
struct is_proto_enum<::protobuf::CharacterState> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::protobuf::CharacterState>() {
  return ::protobuf::CharacterState_descriptor();
}
template <>
struct is_proto_enum<::protobuf::HomeState> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::protobuf::HomeState>() {
  return ::protobuf::HomeState_descriptor();
}
template <>
struct is_proto_enum<::protobuf::ComputeCenterState> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::protobuf::ComputeCenterState>() {
  return ::protobuf::ComputeCenterState_descriptor();
}
template <>
struct is_proto_enum<::protobuf::ResourceState> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::protobuf::ResourceState>() {
  return ::protobuf::ResourceState_descriptor();
}
template <>
struct is_proto_enum<::protobuf::ResourceType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::protobuf::ResourceType>() {
  return ::protobuf::ResourceType_descriptor();
}
template <>
struct is_proto_enum<::protobuf::NewsType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::protobuf::NewsType>() {
  return ::protobuf::NewsType_descriptor();
}
template <>
struct is_proto_enum<::protobuf::GoodsType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::protobuf::GoodsType>() {
  return ::protobuf::GoodsType_descriptor();
}
template <>
struct is_proto_enum<::protobuf::MarketType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::protobuf::MarketType>() {
  return ::protobuf::MarketType_descriptor();
}
template <>
struct is_proto_enum<::protobuf::TechType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::protobuf::TechType>() {
  return ::protobuf::TechType_descriptor();
}
template <>
struct is_proto_enum<::protobuf::AIEventCategory> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::protobuf::AIEventCategory>() {
  return ::protobuf::AIEventCategory_descriptor();
}
template <>
struct is_proto_enum<::protobuf::TaskType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::protobuf::TaskType>() {
  return ::protobuf::TaskType_descriptor();
}
template <>
struct is_proto_enum<::protobuf::AIActionType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::protobuf::AIActionType>() {
  return ::protobuf::AIActionType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // MessageType_2eproto_2epb_2eh
