// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageType.proto

#include "MessageType.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace protobuf {
}  // namespace protobuf
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_MessageType_2eproto[18];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_MessageType_2eproto = nullptr;
const uint32_t TableStruct_MessageType_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_MessageType_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021MessageType.proto\022\010protobuf*D\n\010GameMod"
  "e\022\022\n\016NULL_GAME_MODE\020\000\022\021\n\rGAME_MODE_PVE\020\001"
  "\022\021\n\rGAME_MODE_PVP\020\002*P\n\tGameState\022\023\n\017NULL"
  "_GAME_STATE\020\000\022\016\n\nGAME_START\020\001\022\020\n\014GAME_RU"
  "NNING\020\002\022\014\n\010GAME_END\020\003*}\n\tPlaceType\022\023\n\017NU"
  "LL_PLACE_TYPE\020\000\022\013\n\007FACTORY\020\001\022\t\n\005SPACE\020\002\022"
  "\013\n\007BARRIER\020\003\022\010\n\004BUSH\020\004\022\014\n\010RESOURCE\020\005\022\022\n\016"
  "COMPUTE_CENTER\020\006\022\n\n\006MARKET\020\007*8\n\tShapeTyp"
  "e\022\023\n\017NULL_SHAPE_TYPE\020\000\022\n\n\006CIRCLE\020\001\022\n\n\006SQ"
  "UARE\020\002*;\n\nPlayerType\022\024\n\020NULL_PLAYER_TYPE"
  "\020\000\022\r\n\tCHARACTER\020\001\022\010\n\004TEAM\020\002*R\n\rCharacter"
  "Type\022\027\n\023NULL_CHARACTER_TYPE\020\000\022\t\n\005DRONE\020\001"
  "\022\t\n\005ROBOT\020\002\022\022\n\016AUTONOMOUS_CAR\020\003*\233\002\n\016Char"
  "acterState\022\030\n\024CHARACTER_STATE_NONE\020\000\022\030\n\024"
  "CHARACTER_STATE_IDLE\020\001\022\036\n\032CHARACTER_STAT"
  "E_HARVESTING\020\002\022\035\n\031CHARACTER_STATE_ATTACK"
  "ING\020\003\022\035\n\031CHARACTER_STATE_OCUPPYING\020\004\022\033\n\027"
  "CHARACTER_STATE_TRADING\020\005\022\032\n\026CHARACTER_S"
  "TATE_MOVING\020\006\022 \n\034CHARACTER_STATE_KNOCKED"
  "_BACK\020\007\022\034\n\030CHARACTER_STATE_DECEASED\020\010*\225\001"
  "\n\tHomeState\022\023\n\017NULL_HOME_STATE\020\000\022\023\n\017HOME"
  "_STATE_IDLE\020\001\022 \n\034HOME_STATE_PRODUCING_PR"
  "ODUCT\020\002\022\030\n\024HOME_STATE_REPAIRING\020\003\022\"\n\036HOM"
  "E_STATE_PRODUCING_CHARACTER\020\004*]\n\022Compute"
  "CenterState\022\035\n\031NULL_COMPUTE_CENTER_STATE"
  "\020\000\022\016\n\nOCCUPYABLE\020\001\022\014\n\010OCCUPIED\020\002\022\n\n\006ROBB"
  "ED\020\003*e\n\rResourceState\022\037\n\033NULL_ECONOMY_RE"
  "SOURCE_STSTE\020\000\022\017\n\013HARVESTABLE\020\001\022\023\n\017BEING"
  "_HARVESTED\020\002\022\r\n\tHARVESTED\020\003*c\n\014ResourceT"
  "ype\022\026\n\022NULL_RESOURCE_TYPE\020\000\022\022\n\016SMALL_RES"
  "OURCE\020\001\022\023\n\017MEDIUM_RESOURCE\020\002\022\022\n\016LARGE_RE"
  "SOURCE\020\003*4\n\010NewsType\022\022\n\016NULL_NEWS_TYPE\020\000"
  "\022\010\n\004TEXT\020\001\022\n\n\006BINARY\020\002*b\n\tGoodsType\022\023\n\017N"
  "ULL_GOODS_TYPE\020\000\022\021\n\rSEMICONDUCTOR\020\001\022\014\n\010M"
  "EDICINE\020\002\022\010\n\004TOYS\020\003\022\013\n\007CLOTHES\020\004\022\010\n\004FOOD"
  "\020\005*Y\n\nMarketType\022\024\n\020NULL_MARKET_TYPE\020\000\022\020"
  "\n\014SMALL_MARKET\020\001\022\021\n\rMEDIUM_MARKET\020\002\022\020\n\014L"
  "ARGE_MARKET\020\003*\236\002\n\010TechType\022\022\n\016NULL_TECH_"
  "TYPE\020\000\022\017\n\013INCREASE_HP\020\001\022\031\n\025INCREASE_ATTA"
  "CK_POWER\020\002\022\030\n\024INCREASE_ATTACK_SIZE\020\003\022\023\n\017"
  "INCREASE_ROBUST\020\004\022\027\n\023INCREASE_MOVE_SPEED"
  "\020\005\022\033\n\027INCREASE_CARRY_CAPACITY\020\006\022\027\n\023INCRE"
  "ASE_EFFICIENCY\020\007\022\027\n\023INCREASE_PRODUCTION\020"
  "\010\022\024\n\020INCREASE_STORAGE\020\t\022\022\n\016INCREASE_PRIC"
  "E\020\n\022\021\n\rDECREASE_COST\020\013*|\n\017AIEventCategor"
  "y\022\032\n\026NULL_AI_EVENT_CATEGORY\020\000\022\022\n\016ECONOMI"
  "C_EVENT\020\001\022\021\n\rWEATHER_EVENT\020\002\022\024\n\020TECHNOLO"
  "GY_EVENT\020\003\022\020\n\014COMBAT_EVENT\020\004*m\n\010TaskType"
  "\022\022\n\016NULL_TASK_TYPE\020\000\022\023\n\017PRODUCE_PRODUCT\020"
  "\001\022\024\n\020HARVEST_RESOURCE\020\002\022\021\n\rOCCUPY_CENTER"
  "\020\003\022\017\n\013REPAIR_UNIT\020\004*m\n\014AIActionType\022\013\n\007U"
  "NKNOWN\020\000\022\013\n\007PRODUCE\020\001\022\013\n\007HARVEST\020\002\022\010\n\004MO"
  "VE\020\003\022\n\n\006ATTACK\020\004\022\n\n\006REPAIR\020\005\022\010\n\004SELL\020\006\022\n"
  "\n\006OCCUPY\020\007b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_MessageType_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_MessageType_2eproto = {
    false, false, 2138, descriptor_table_protodef_MessageType_2eproto,
    "MessageType.proto",
    &descriptor_table_MessageType_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_MessageType_2eproto::offsets,
    nullptr, file_level_enum_descriptors_MessageType_2eproto,
    file_level_service_descriptors_MessageType_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_MessageType_2eproto_getter() {
  return &descriptor_table_MessageType_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_MessageType_2eproto(&descriptor_table_MessageType_2eproto);
namespace protobuf {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GameMode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[0];
}
bool GameMode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GameState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[1];
}
bool GameState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PlaceType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[2];
}
bool PlaceType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ShapeType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[3];
}
bool ShapeType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PlayerType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[4];
}
bool PlayerType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CharacterType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[5];
}
bool CharacterType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CharacterState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[6];
}
bool CharacterState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* HomeState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[7];
}
bool HomeState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ComputeCenterState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[8];
}
bool ComputeCenterState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ResourceState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[9];
}
bool ResourceState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ResourceType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[10];
}
bool ResourceType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* NewsType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[11];
}
bool NewsType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* GoodsType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[12];
}
bool GoodsType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MarketType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[13];
}
bool MarketType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TechType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[14];
}
bool TechType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AIEventCategory_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[15];
}
bool AIEventCategory_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* TaskType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[16];
}
bool TaskType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AIActionType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_MessageType_2eproto);
  return file_level_enum_descriptors_MessageType_2eproto[17];
}
bool AIActionType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
