// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Services.proto

#include "Services.pb.h"
#include "Services.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace protobuf {

static const char* AvailableService_method_names[] = {
  "/protobuf.AvailableService/TryConnection",
  "/protobuf.AvailableService/RegisterFactory",
  "/protobuf.AvailableService/GetMap",
  "/protobuf.AvailableService/Move",
  "/protobuf.AvailableService/Recover",
  "/protobuf.AvailableService/Harvest",
  "/protobuf.AvailableService/Attack",
  "/protobuf.AvailableService/Occupy",
  "/protobuf.AvailableService/Send",
  "/protobuf.AvailableService/Load",
  "/protobuf.AvailableService/Trade",
  "/protobuf.AvailableService/CreateCharacter",
  "/protobuf.AvailableService/CreateCharacterRID",
  "/protobuf.AvailableService/Produce",
  "/protobuf.AvailableService/UplevelTech",
  "/protobuf.AvailableService/EndAllAction",
  "/protobuf.AvailableService/AskAI",
};

std::unique_ptr< AvailableService::Stub> AvailableService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AvailableService::Stub> stub(new AvailableService::Stub(channel, options));
  return stub;
}

AvailableService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_TryConnection_(AvailableService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RegisterFactory_(AvailableService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_GetMap_(AvailableService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Move_(AvailableService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Recover_(AvailableService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Harvest_(AvailableService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Attack_(AvailableService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Occupy_(AvailableService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Send_(AvailableService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Load_(AvailableService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Trade_(AvailableService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateCharacter_(AvailableService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateCharacterRID_(AvailableService_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Produce_(AvailableService_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UplevelTech_(AvailableService_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_EndAllAction_(AvailableService_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AskAI_(AvailableService_method_names[16], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AvailableService::Stub::TryConnection(::grpc::ClientContext* context, const ::protobuf::IDMsg& request, ::protobuf::BoolRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::protobuf::IDMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_TryConnection_, context, request, response);
}

void AvailableService::Stub::async::TryConnection(::grpc::ClientContext* context, const ::protobuf::IDMsg* request, ::protobuf::BoolRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::protobuf::IDMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TryConnection_, context, request, response, std::move(f));
}

void AvailableService::Stub::async::TryConnection(::grpc::ClientContext* context, const ::protobuf::IDMsg* request, ::protobuf::BoolRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TryConnection_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::PrepareAsyncTryConnectionRaw(::grpc::ClientContext* context, const ::protobuf::IDMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::protobuf::BoolRes, ::protobuf::IDMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_TryConnection_, context, request);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::AsyncTryConnectionRaw(::grpc::ClientContext* context, const ::protobuf::IDMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTryConnectionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::protobuf::MessageToClient>* AvailableService::Stub::RegisterFactoryRaw(::grpc::ClientContext* context, const ::protobuf::RegisterFactoryMsg& request) {
  return ::grpc::internal::ClientReaderFactory< ::protobuf::MessageToClient>::Create(channel_.get(), rpcmethod_RegisterFactory_, context, request);
}

void AvailableService::Stub::async::RegisterFactory(::grpc::ClientContext* context, const ::protobuf::RegisterFactoryMsg* request, ::grpc::ClientReadReactor< ::protobuf::MessageToClient>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::protobuf::MessageToClient>::Create(stub_->channel_.get(), stub_->rpcmethod_RegisterFactory_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::protobuf::MessageToClient>* AvailableService::Stub::AsyncRegisterFactoryRaw(::grpc::ClientContext* context, const ::protobuf::RegisterFactoryMsg& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::protobuf::MessageToClient>::Create(channel_.get(), cq, rpcmethod_RegisterFactory_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::protobuf::MessageToClient>* AvailableService::Stub::PrepareAsyncRegisterFactoryRaw(::grpc::ClientContext* context, const ::protobuf::RegisterFactoryMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::protobuf::MessageToClient>::Create(channel_.get(), cq, rpcmethod_RegisterFactory_, context, request, false, nullptr);
}

::grpc::Status AvailableService::Stub::GetMap(::grpc::ClientContext* context, const ::protobuf::NullRequest& request, ::protobuf::MessageOfMap* response) {
  return ::grpc::internal::BlockingUnaryCall< ::protobuf::NullRequest, ::protobuf::MessageOfMap, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetMap_, context, request, response);
}

void AvailableService::Stub::async::GetMap(::grpc::ClientContext* context, const ::protobuf::NullRequest* request, ::protobuf::MessageOfMap* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::protobuf::NullRequest, ::protobuf::MessageOfMap, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMap_, context, request, response, std::move(f));
}

void AvailableService::Stub::async::GetMap(::grpc::ClientContext* context, const ::protobuf::NullRequest* request, ::protobuf::MessageOfMap* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetMap_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protobuf::MessageOfMap>* AvailableService::Stub::PrepareAsyncGetMapRaw(::grpc::ClientContext* context, const ::protobuf::NullRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::protobuf::MessageOfMap, ::protobuf::NullRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetMap_, context, request);
}

::grpc::ClientAsyncResponseReader< ::protobuf::MessageOfMap>* AvailableService::Stub::AsyncGetMapRaw(::grpc::ClientContext* context, const ::protobuf::NullRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetMapRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AvailableService::Stub::Move(::grpc::ClientContext* context, const ::protobuf::MoveMsg& request, ::protobuf::MoveRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::protobuf::MoveMsg, ::protobuf::MoveRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Move_, context, request, response);
}

void AvailableService::Stub::async::Move(::grpc::ClientContext* context, const ::protobuf::MoveMsg* request, ::protobuf::MoveRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::protobuf::MoveMsg, ::protobuf::MoveRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Move_, context, request, response, std::move(f));
}

void AvailableService::Stub::async::Move(::grpc::ClientContext* context, const ::protobuf::MoveMsg* request, ::protobuf::MoveRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Move_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protobuf::MoveRes>* AvailableService::Stub::PrepareAsyncMoveRaw(::grpc::ClientContext* context, const ::protobuf::MoveMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::protobuf::MoveRes, ::protobuf::MoveMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Move_, context, request);
}

::grpc::ClientAsyncResponseReader< ::protobuf::MoveRes>* AvailableService::Stub::AsyncMoveRaw(::grpc::ClientContext* context, const ::protobuf::MoveMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMoveRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AvailableService::Stub::Recover(::grpc::ClientContext* context, const ::protobuf::RecoverMsg& request, ::protobuf::BoolRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::protobuf::RecoverMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Recover_, context, request, response);
}

void AvailableService::Stub::async::Recover(::grpc::ClientContext* context, const ::protobuf::RecoverMsg* request, ::protobuf::BoolRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::protobuf::RecoverMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Recover_, context, request, response, std::move(f));
}

void AvailableService::Stub::async::Recover(::grpc::ClientContext* context, const ::protobuf::RecoverMsg* request, ::protobuf::BoolRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Recover_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::PrepareAsyncRecoverRaw(::grpc::ClientContext* context, const ::protobuf::RecoverMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::protobuf::BoolRes, ::protobuf::RecoverMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Recover_, context, request);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::AsyncRecoverRaw(::grpc::ClientContext* context, const ::protobuf::RecoverMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRecoverRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AvailableService::Stub::Harvest(::grpc::ClientContext* context, const ::protobuf::ResourceMsg& request, ::protobuf::BoolRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::protobuf::ResourceMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Harvest_, context, request, response);
}

void AvailableService::Stub::async::Harvest(::grpc::ClientContext* context, const ::protobuf::ResourceMsg* request, ::protobuf::BoolRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::protobuf::ResourceMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Harvest_, context, request, response, std::move(f));
}

void AvailableService::Stub::async::Harvest(::grpc::ClientContext* context, const ::protobuf::ResourceMsg* request, ::protobuf::BoolRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Harvest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::PrepareAsyncHarvestRaw(::grpc::ClientContext* context, const ::protobuf::ResourceMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::protobuf::BoolRes, ::protobuf::ResourceMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Harvest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::AsyncHarvestRaw(::grpc::ClientContext* context, const ::protobuf::ResourceMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHarvestRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AvailableService::Stub::Attack(::grpc::ClientContext* context, const ::protobuf::AttackMsg& request, ::protobuf::BoolRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::protobuf::AttackMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Attack_, context, request, response);
}

void AvailableService::Stub::async::Attack(::grpc::ClientContext* context, const ::protobuf::AttackMsg* request, ::protobuf::BoolRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::protobuf::AttackMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Attack_, context, request, response, std::move(f));
}

void AvailableService::Stub::async::Attack(::grpc::ClientContext* context, const ::protobuf::AttackMsg* request, ::protobuf::BoolRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Attack_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::PrepareAsyncAttackRaw(::grpc::ClientContext* context, const ::protobuf::AttackMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::protobuf::BoolRes, ::protobuf::AttackMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Attack_, context, request);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::AsyncAttackRaw(::grpc::ClientContext* context, const ::protobuf::AttackMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAttackRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AvailableService::Stub::Occupy(::grpc::ClientContext* context, const ::protobuf::OccupyMsg& request, ::protobuf::BoolRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::protobuf::OccupyMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Occupy_, context, request, response);
}

void AvailableService::Stub::async::Occupy(::grpc::ClientContext* context, const ::protobuf::OccupyMsg* request, ::protobuf::BoolRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::protobuf::OccupyMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Occupy_, context, request, response, std::move(f));
}

void AvailableService::Stub::async::Occupy(::grpc::ClientContext* context, const ::protobuf::OccupyMsg* request, ::protobuf::BoolRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Occupy_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::PrepareAsyncOccupyRaw(::grpc::ClientContext* context, const ::protobuf::OccupyMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::protobuf::BoolRes, ::protobuf::OccupyMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Occupy_, context, request);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::AsyncOccupyRaw(::grpc::ClientContext* context, const ::protobuf::OccupyMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncOccupyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AvailableService::Stub::Send(::grpc::ClientContext* context, const ::protobuf::SendMsg& request, ::protobuf::BoolRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::protobuf::SendMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Send_, context, request, response);
}

void AvailableService::Stub::async::Send(::grpc::ClientContext* context, const ::protobuf::SendMsg* request, ::protobuf::BoolRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::protobuf::SendMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Send_, context, request, response, std::move(f));
}

void AvailableService::Stub::async::Send(::grpc::ClientContext* context, const ::protobuf::SendMsg* request, ::protobuf::BoolRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Send_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::PrepareAsyncSendRaw(::grpc::ClientContext* context, const ::protobuf::SendMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::protobuf::BoolRes, ::protobuf::SendMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Send_, context, request);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::AsyncSendRaw(::grpc::ClientContext* context, const ::protobuf::SendMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AvailableService::Stub::Load(::grpc::ClientContext* context, const ::protobuf::LoadMsg& request, ::protobuf::BoolRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::protobuf::LoadMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Load_, context, request, response);
}

void AvailableService::Stub::async::Load(::grpc::ClientContext* context, const ::protobuf::LoadMsg* request, ::protobuf::BoolRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::protobuf::LoadMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Load_, context, request, response, std::move(f));
}

void AvailableService::Stub::async::Load(::grpc::ClientContext* context, const ::protobuf::LoadMsg* request, ::protobuf::BoolRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Load_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::PrepareAsyncLoadRaw(::grpc::ClientContext* context, const ::protobuf::LoadMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::protobuf::BoolRes, ::protobuf::LoadMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Load_, context, request);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::AsyncLoadRaw(::grpc::ClientContext* context, const ::protobuf::LoadMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoadRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AvailableService::Stub::Trade(::grpc::ClientContext* context, const ::protobuf::TradeMsg& request, ::protobuf::BoolRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::protobuf::TradeMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Trade_, context, request, response);
}

void AvailableService::Stub::async::Trade(::grpc::ClientContext* context, const ::protobuf::TradeMsg* request, ::protobuf::BoolRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::protobuf::TradeMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Trade_, context, request, response, std::move(f));
}

void AvailableService::Stub::async::Trade(::grpc::ClientContext* context, const ::protobuf::TradeMsg* request, ::protobuf::BoolRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Trade_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::PrepareAsyncTradeRaw(::grpc::ClientContext* context, const ::protobuf::TradeMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::protobuf::BoolRes, ::protobuf::TradeMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Trade_, context, request);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::AsyncTradeRaw(::grpc::ClientContext* context, const ::protobuf::TradeMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTradeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AvailableService::Stub::CreateCharacter(::grpc::ClientContext* context, const ::protobuf::CreateCharacterMsg& request, ::protobuf::BoolRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::protobuf::CreateCharacterMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateCharacter_, context, request, response);
}

void AvailableService::Stub::async::CreateCharacter(::grpc::ClientContext* context, const ::protobuf::CreateCharacterMsg* request, ::protobuf::BoolRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::protobuf::CreateCharacterMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateCharacter_, context, request, response, std::move(f));
}

void AvailableService::Stub::async::CreateCharacter(::grpc::ClientContext* context, const ::protobuf::CreateCharacterMsg* request, ::protobuf::BoolRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateCharacter_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::PrepareAsyncCreateCharacterRaw(::grpc::ClientContext* context, const ::protobuf::CreateCharacterMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::protobuf::BoolRes, ::protobuf::CreateCharacterMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateCharacter_, context, request);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::AsyncCreateCharacterRaw(::grpc::ClientContext* context, const ::protobuf::CreateCharacterMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateCharacterRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AvailableService::Stub::CreateCharacterRID(::grpc::ClientContext* context, const ::protobuf::CreateCharacterMsg& request, ::protobuf::CreatCharacterRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::protobuf::CreateCharacterMsg, ::protobuf::CreatCharacterRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateCharacterRID_, context, request, response);
}

void AvailableService::Stub::async::CreateCharacterRID(::grpc::ClientContext* context, const ::protobuf::CreateCharacterMsg* request, ::protobuf::CreatCharacterRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::protobuf::CreateCharacterMsg, ::protobuf::CreatCharacterRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateCharacterRID_, context, request, response, std::move(f));
}

void AvailableService::Stub::async::CreateCharacterRID(::grpc::ClientContext* context, const ::protobuf::CreateCharacterMsg* request, ::protobuf::CreatCharacterRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateCharacterRID_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protobuf::CreatCharacterRes>* AvailableService::Stub::PrepareAsyncCreateCharacterRIDRaw(::grpc::ClientContext* context, const ::protobuf::CreateCharacterMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::protobuf::CreatCharacterRes, ::protobuf::CreateCharacterMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateCharacterRID_, context, request);
}

::grpc::ClientAsyncResponseReader< ::protobuf::CreatCharacterRes>* AvailableService::Stub::AsyncCreateCharacterRIDRaw(::grpc::ClientContext* context, const ::protobuf::CreateCharacterMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateCharacterRIDRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AvailableService::Stub::Produce(::grpc::ClientContext* context, const ::protobuf::ProduceGoodsMsg& request, ::protobuf::BoolRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::protobuf::ProduceGoodsMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Produce_, context, request, response);
}

void AvailableService::Stub::async::Produce(::grpc::ClientContext* context, const ::protobuf::ProduceGoodsMsg* request, ::protobuf::BoolRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::protobuf::ProduceGoodsMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Produce_, context, request, response, std::move(f));
}

void AvailableService::Stub::async::Produce(::grpc::ClientContext* context, const ::protobuf::ProduceGoodsMsg* request, ::protobuf::BoolRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Produce_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::PrepareAsyncProduceRaw(::grpc::ClientContext* context, const ::protobuf::ProduceGoodsMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::protobuf::BoolRes, ::protobuf::ProduceGoodsMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Produce_, context, request);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::AsyncProduceRaw(::grpc::ClientContext* context, const ::protobuf::ProduceGoodsMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncProduceRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AvailableService::Stub::UplevelTech(::grpc::ClientContext* context, const ::protobuf::UplevelTechMsg& request, ::protobuf::BoolRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::protobuf::UplevelTechMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UplevelTech_, context, request, response);
}

void AvailableService::Stub::async::UplevelTech(::grpc::ClientContext* context, const ::protobuf::UplevelTechMsg* request, ::protobuf::BoolRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::protobuf::UplevelTechMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UplevelTech_, context, request, response, std::move(f));
}

void AvailableService::Stub::async::UplevelTech(::grpc::ClientContext* context, const ::protobuf::UplevelTechMsg* request, ::protobuf::BoolRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UplevelTech_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::PrepareAsyncUplevelTechRaw(::grpc::ClientContext* context, const ::protobuf::UplevelTechMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::protobuf::BoolRes, ::protobuf::UplevelTechMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UplevelTech_, context, request);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::AsyncUplevelTechRaw(::grpc::ClientContext* context, const ::protobuf::UplevelTechMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUplevelTechRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AvailableService::Stub::EndAllAction(::grpc::ClientContext* context, const ::protobuf::IDMsg& request, ::protobuf::BoolRes* response) {
  return ::grpc::internal::BlockingUnaryCall< ::protobuf::IDMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_EndAllAction_, context, request, response);
}

void AvailableService::Stub::async::EndAllAction(::grpc::ClientContext* context, const ::protobuf::IDMsg* request, ::protobuf::BoolRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::protobuf::IDMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EndAllAction_, context, request, response, std::move(f));
}

void AvailableService::Stub::async::EndAllAction(::grpc::ClientContext* context, const ::protobuf::IDMsg* request, ::protobuf::BoolRes* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_EndAllAction_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::PrepareAsyncEndAllActionRaw(::grpc::ClientContext* context, const ::protobuf::IDMsg& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::protobuf::BoolRes, ::protobuf::IDMsg, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_EndAllAction_, context, request);
}

::grpc::ClientAsyncResponseReader< ::protobuf::BoolRes>* AvailableService::Stub::AsyncEndAllActionRaw(::grpc::ClientContext* context, const ::protobuf::IDMsg& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncEndAllActionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AvailableService::Stub::AskAI(::grpc::ClientContext* context, const ::protobuf::StrategicAIRequest& request, ::protobuf::StrategicAIResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::protobuf::StrategicAIRequest, ::protobuf::StrategicAIResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AskAI_, context, request, response);
}

void AvailableService::Stub::async::AskAI(::grpc::ClientContext* context, const ::protobuf::StrategicAIRequest* request, ::protobuf::StrategicAIResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::protobuf::StrategicAIRequest, ::protobuf::StrategicAIResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AskAI_, context, request, response, std::move(f));
}

void AvailableService::Stub::async::AskAI(::grpc::ClientContext* context, const ::protobuf::StrategicAIRequest* request, ::protobuf::StrategicAIResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AskAI_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::protobuf::StrategicAIResponse>* AvailableService::Stub::PrepareAsyncAskAIRaw(::grpc::ClientContext* context, const ::protobuf::StrategicAIRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::protobuf::StrategicAIResponse, ::protobuf::StrategicAIRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AskAI_, context, request);
}

::grpc::ClientAsyncResponseReader< ::protobuf::StrategicAIResponse>* AvailableService::Stub::AsyncAskAIRaw(::grpc::ClientContext* context, const ::protobuf::StrategicAIRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAskAIRaw(context, request, cq);
  result->StartCall();
  return result;
}

AvailableService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AvailableService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AvailableService::Service, ::protobuf::IDMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AvailableService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::protobuf::IDMsg* req,
             ::protobuf::BoolRes* resp) {
               return service->TryConnection(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AvailableService_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< AvailableService::Service, ::protobuf::RegisterFactoryMsg, ::protobuf::MessageToClient>(
          [](AvailableService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::protobuf::RegisterFactoryMsg* req,
             ::grpc::ServerWriter<::protobuf::MessageToClient>* writer) {
               return service->RegisterFactory(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AvailableService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AvailableService::Service, ::protobuf::NullRequest, ::protobuf::MessageOfMap, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AvailableService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::protobuf::NullRequest* req,
             ::protobuf::MessageOfMap* resp) {
               return service->GetMap(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AvailableService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AvailableService::Service, ::protobuf::MoveMsg, ::protobuf::MoveRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AvailableService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::protobuf::MoveMsg* req,
             ::protobuf::MoveRes* resp) {
               return service->Move(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AvailableService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AvailableService::Service, ::protobuf::RecoverMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AvailableService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::protobuf::RecoverMsg* req,
             ::protobuf::BoolRes* resp) {
               return service->Recover(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AvailableService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AvailableService::Service, ::protobuf::ResourceMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AvailableService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::protobuf::ResourceMsg* req,
             ::protobuf::BoolRes* resp) {
               return service->Harvest(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AvailableService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AvailableService::Service, ::protobuf::AttackMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AvailableService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::protobuf::AttackMsg* req,
             ::protobuf::BoolRes* resp) {
               return service->Attack(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AvailableService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AvailableService::Service, ::protobuf::OccupyMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AvailableService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::protobuf::OccupyMsg* req,
             ::protobuf::BoolRes* resp) {
               return service->Occupy(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AvailableService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AvailableService::Service, ::protobuf::SendMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AvailableService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::protobuf::SendMsg* req,
             ::protobuf::BoolRes* resp) {
               return service->Send(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AvailableService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AvailableService::Service, ::protobuf::LoadMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AvailableService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::protobuf::LoadMsg* req,
             ::protobuf::BoolRes* resp) {
               return service->Load(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AvailableService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AvailableService::Service, ::protobuf::TradeMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AvailableService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::protobuf::TradeMsg* req,
             ::protobuf::BoolRes* resp) {
               return service->Trade(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AvailableService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AvailableService::Service, ::protobuf::CreateCharacterMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AvailableService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::protobuf::CreateCharacterMsg* req,
             ::protobuf::BoolRes* resp) {
               return service->CreateCharacter(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AvailableService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AvailableService::Service, ::protobuf::CreateCharacterMsg, ::protobuf::CreatCharacterRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AvailableService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::protobuf::CreateCharacterMsg* req,
             ::protobuf::CreatCharacterRes* resp) {
               return service->CreateCharacterRID(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AvailableService_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AvailableService::Service, ::protobuf::ProduceGoodsMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AvailableService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::protobuf::ProduceGoodsMsg* req,
             ::protobuf::BoolRes* resp) {
               return service->Produce(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AvailableService_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AvailableService::Service, ::protobuf::UplevelTechMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AvailableService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::protobuf::UplevelTechMsg* req,
             ::protobuf::BoolRes* resp) {
               return service->UplevelTech(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AvailableService_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AvailableService::Service, ::protobuf::IDMsg, ::protobuf::BoolRes, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AvailableService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::protobuf::IDMsg* req,
             ::protobuf::BoolRes* resp) {
               return service->EndAllAction(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AvailableService_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AvailableService::Service, ::protobuf::StrategicAIRequest, ::protobuf::StrategicAIResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AvailableService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::protobuf::StrategicAIRequest* req,
             ::protobuf::StrategicAIResponse* resp) {
               return service->AskAI(ctx, req, resp);
             }, this)));
}

AvailableService::Service::~Service() {
}

::grpc::Status AvailableService::Service::TryConnection(::grpc::ServerContext* context, const ::protobuf::IDMsg* request, ::protobuf::BoolRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AvailableService::Service::RegisterFactory(::grpc::ServerContext* context, const ::protobuf::RegisterFactoryMsg* request, ::grpc::ServerWriter< ::protobuf::MessageToClient>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AvailableService::Service::GetMap(::grpc::ServerContext* context, const ::protobuf::NullRequest* request, ::protobuf::MessageOfMap* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AvailableService::Service::Move(::grpc::ServerContext* context, const ::protobuf::MoveMsg* request, ::protobuf::MoveRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AvailableService::Service::Recover(::grpc::ServerContext* context, const ::protobuf::RecoverMsg* request, ::protobuf::BoolRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AvailableService::Service::Harvest(::grpc::ServerContext* context, const ::protobuf::ResourceMsg* request, ::protobuf::BoolRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AvailableService::Service::Attack(::grpc::ServerContext* context, const ::protobuf::AttackMsg* request, ::protobuf::BoolRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AvailableService::Service::Occupy(::grpc::ServerContext* context, const ::protobuf::OccupyMsg* request, ::protobuf::BoolRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AvailableService::Service::Send(::grpc::ServerContext* context, const ::protobuf::SendMsg* request, ::protobuf::BoolRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AvailableService::Service::Load(::grpc::ServerContext* context, const ::protobuf::LoadMsg* request, ::protobuf::BoolRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AvailableService::Service::Trade(::grpc::ServerContext* context, const ::protobuf::TradeMsg* request, ::protobuf::BoolRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AvailableService::Service::CreateCharacter(::grpc::ServerContext* context, const ::protobuf::CreateCharacterMsg* request, ::protobuf::BoolRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AvailableService::Service::CreateCharacterRID(::grpc::ServerContext* context, const ::protobuf::CreateCharacterMsg* request, ::protobuf::CreatCharacterRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AvailableService::Service::Produce(::grpc::ServerContext* context, const ::protobuf::ProduceGoodsMsg* request, ::protobuf::BoolRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AvailableService::Service::UplevelTech(::grpc::ServerContext* context, const ::protobuf::UplevelTechMsg* request, ::protobuf::BoolRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AvailableService::Service::EndAllAction(::grpc::ServerContext* context, const ::protobuf::IDMsg* request, ::protobuf::BoolRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AvailableService::Service::AskAI(::grpc::ServerContext* context, const ::protobuf::StrategicAIRequest* request, ::protobuf::StrategicAIResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace protobuf

