// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Services.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf {

  /// <summary>Holder for reflection information generated from Services.proto</summary>
  public static partial class ServicesReflection {

    #region Descriptor
    /// <summary>File descriptor for Services.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServicesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5TZXJ2aWNlcy5wcm90bxIIcHJvdG9idWYaFU1lc3NhZ2UyQ2xpZW50cy5w",
            "cm90bxoUTWVzc2FnZTJTZXJ2ZXIucHJvdG8yrwgKEEF2YWlsYWJsZVNlcnZp",
            "Y2USMwoNVHJ5Q29ubmVjdGlvbhIPLnByb3RvYnVmLklETXNnGhEucHJvdG9i",
            "dWYuQm9vbFJlcxJMCg9SZWdpc3RlckZhY3RvcnkSHC5wcm90b2J1Zi5SZWdp",
            "c3RlckZhY3RvcnlNc2caGS5wcm90b2J1Zi5NZXNzYWdlVG9DbGllbnQwARI3",
            "CgZHZXRNYXASFS5wcm90b2J1Zi5OdWxsUmVxdWVzdBoWLnByb3RvYnVmLk1l",
            "c3NhZ2VPZk1hcBIsCgRNb3ZlEhEucHJvdG9idWYuTW92ZU1zZxoRLnByb3Rv",
            "YnVmLk1vdmVSZXMSMgoHUmVjb3ZlchIULnByb3RvYnVmLlJlY292ZXJNc2ca",
            "ES5wcm90b2J1Zi5Cb29sUmVzEjMKB0hhcnZlc3QSFS5wcm90b2J1Zi5SZXNv",
            "dXJjZU1zZxoRLnByb3RvYnVmLkJvb2xSZXMSMAoGQXR0YWNrEhMucHJvdG9i",
            "dWYuQXR0YWNrTXNnGhEucHJvdG9idWYuQm9vbFJlcxIwCgZPY2N1cHkSEy5w",
            "cm90b2J1Zi5PY2N1cHlNc2caES5wcm90b2J1Zi5Cb29sUmVzEiwKBFNlbmQS",
            "ES5wcm90b2J1Zi5TZW5kTXNnGhEucHJvdG9idWYuQm9vbFJlcxIsCgRMb2Fk",
            "EhEucHJvdG9idWYuTG9hZE1zZxoRLnByb3RvYnVmLkJvb2xSZXMSLgoFVHJh",
            "ZGUSEi5wcm90b2J1Zi5UcmFkZU1zZxoRLnByb3RvYnVmLkJvb2xSZXMSQgoP",
            "Q3JlYXRlQ2hhcmFjdGVyEhwucHJvdG9idWYuQ3JlYXRlQ2hhcmFjdGVyTXNn",
            "GhEucHJvdG9idWYuQm9vbFJlcxJPChJDcmVhdGVDaGFyYWN0ZXJSSUQSHC5w",
            "cm90b2J1Zi5DcmVhdGVDaGFyYWN0ZXJNc2caGy5wcm90b2J1Zi5DcmVhdENo",
            "YXJhY3RlclJlcxI3CgdQcm9kdWNlEhkucHJvdG9idWYuUHJvZHVjZUdvb2Rz",
            "TXNnGhEucHJvdG9idWYuQm9vbFJlcxI6CgtVcGxldmVsVGVjaBIYLnByb3Rv",
            "YnVmLlVwbGV2ZWxUZWNoTXNnGhEucHJvdG9idWYuQm9vbFJlcxIyCgxFbmRB",
            "bGxBY3Rpb24SDy5wcm90b2J1Zi5JRE1zZxoRLnByb3RvYnVmLkJvb2xSZXMS",
            "RAoFQXNrQUkSHC5wcm90b2J1Zi5TdHJhdGVnaWNBSVJlcXVlc3QaHS5wcm90",
            "b2J1Zi5TdHJhdGVnaWNBSVJlc3BvbnNlElQKFUdldEN1cnJlbnRFdmVudFN0",
            "YXR1cxIcLnByb3RvYnVmLkV2ZW50U3RhdHVzUmVxdWVzdBodLnByb3RvYnVm",
            "LkV2ZW50U3RhdHVzUmVzcG9uc2ViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Protobuf.Message2ClientsReflection.Descriptor, global::Protobuf.Message2ServerReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
