// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MessageType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf {

  /// <summary>Holder for reflection information generated from MessageType.proto</summary>
  public static partial class MessageTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for MessageType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFNZXNzYWdlVHlwZS5wcm90bxIIcHJvdG9idWYqRAoIR2FtZU1vZGUSEgoO",
            "TlVMTF9HQU1FX01PREUQABIRCg1HQU1FX01PREVfUFZFEAESEQoNR0FNRV9N",
            "T0RFX1BWUBACKlAKCUdhbWVTdGF0ZRITCg9OVUxMX0dBTUVfU1RBVEUQABIO",
            "CgpHQU1FX1NUQVJUEAESEAoMR0FNRV9SVU5OSU5HEAISDAoIR0FNRV9FTkQQ",
            "Ayp9CglQbGFjZVR5cGUSEwoPTlVMTF9QTEFDRV9UWVBFEAASCwoHRkFDVE9S",
            "WRABEgkKBVNQQUNFEAISCwoHQkFSUklFUhADEggKBEJVU0gQBBIMCghSRVNP",
            "VVJDRRAFEhIKDkNPTVBVVEVfQ0VOVEVSEAYSCgoGTUFSS0VUEAcqOAoJU2hh",
            "cGVUeXBlEhMKD05VTExfU0hBUEVfVFlQRRAAEgoKBkNJUkNMRRABEgoKBlNR",
            "VUFSRRACKjsKClBsYXllclR5cGUSFAoQTlVMTF9QTEFZRVJfVFlQRRAAEg0K",
            "CUNIQVJBQ1RFUhABEggKBFRFQU0QAipSCg1DaGFyYWN0ZXJUeXBlEhcKE05V",
            "TExfQ0hBUkFDVEVSX1RZUEUQABIJCgVEUk9ORRABEgkKBVJPQk9UEAISEgoO",
            "QVVUT05PTU9VU19DQVIQAyqbAgoOQ2hhcmFjdGVyU3RhdGUSGAoUQ0hBUkFD",
            "VEVSX1NUQVRFX05PTkUQABIYChRDSEFSQUNURVJfU1RBVEVfSURMRRABEh4K",
            "GkNIQVJBQ1RFUl9TVEFURV9IQVJWRVNUSU5HEAISHQoZQ0hBUkFDVEVSX1NU",
            "QVRFX0FUVEFDS0lORxADEh0KGUNIQVJBQ1RFUl9TVEFURV9PQ1VQUFlJTkcQ",
            "BBIbChdDSEFSQUNURVJfU1RBVEVfVFJBRElORxAFEhoKFkNIQVJBQ1RFUl9T",
            "VEFURV9NT1ZJTkcQBhIgChxDSEFSQUNURVJfU1RBVEVfS05PQ0tFRF9CQUNL",
            "EAcSHAoYQ0hBUkFDVEVSX1NUQVRFX0RFQ0VBU0VEEAgqlQEKCUhvbWVTdGF0",
            "ZRITCg9OVUxMX0hPTUVfU1RBVEUQABITCg9IT01FX1NUQVRFX0lETEUQARIg",
            "ChxIT01FX1NUQVRFX1BST0RVQ0lOR19QUk9EVUNUEAISGAoUSE9NRV9TVEFU",
            "RV9SRVBBSVJJTkcQAxIiCh5IT01FX1NUQVRFX1BST0RVQ0lOR19DSEFSQUNU",
            "RVIQBCpdChJDb21wdXRlQ2VudGVyU3RhdGUSHQoZTlVMTF9DT01QVVRFX0NF",
            "TlRFUl9TVEFURRAAEg4KCk9DQ1VQWUFCTEUQARIMCghPQ0NVUElFRBACEgoK",
            "BlJPQkJFRBADKmUKDVJlc291cmNlU3RhdGUSHwobTlVMTF9FQ09OT01ZX1JF",
            "U09VUkNFX1NUU1RFEAASDwoLSEFSVkVTVEFCTEUQARITCg9CRUlOR19IQVJW",
            "RVNURUQQAhINCglIQVJWRVNURUQQAypjCgxSZXNvdXJjZVR5cGUSFgoSTlVM",
            "TF9SRVNPVVJDRV9UWVBFEAASEgoOU01BTExfUkVTT1VSQ0UQARITCg9NRURJ",
            "VU1fUkVTT1VSQ0UQAhISCg5MQVJHRV9SRVNPVVJDRRADKjQKCE5ld3NUeXBl",
            "EhIKDk5VTExfTkVXU19UWVBFEAASCAoEVEVYVBABEgoKBkJJTkFSWRACKmIK",
            "CUdvb2RzVHlwZRITCg9OVUxMX0dPT0RTX1RZUEUQABIRCg1TRU1JQ09ORFVD",
            "VE9SEAESDAoITUVESUNJTkUQAhIICgRUT1lTEAMSCwoHQ0xPVEhFUxAEEggK",
            "BEZPT0QQBSpZCgpNYXJrZXRUeXBlEhQKEE5VTExfTUFSS0VUX1RZUEUQABIQ",
            "CgxTTUFMTF9NQVJLRVQQARIRCg1NRURJVU1fTUFSS0VUEAISEAoMTEFSR0Vf",
            "TUFSS0VUEAMqngIKCFRlY2hUeXBlEhIKDk5VTExfVEVDSF9UWVBFEAASDwoL",
            "SU5DUkVBU0VfSFAQARIZChVJTkNSRUFTRV9BVFRBQ0tfUE9XRVIQAhIYChRJ",
            "TkNSRUFTRV9BVFRBQ0tfU0laRRADEhMKD0lOQ1JFQVNFX1JPQlVTVBAEEhcK",
            "E0lOQ1JFQVNFX01PVkVfU1BFRUQQBRIbChdJTkNSRUFTRV9DQVJSWV9DQVBB",
            "Q0lUWRAGEhcKE0lOQ1JFQVNFX0VGRklDSUVOQ1kQBxIXChNJTkNSRUFTRV9Q",
            "Uk9EVUNUSU9OEAgSFAoQSU5DUkVBU0VfU1RPUkFHRRAJEhIKDklOQ1JFQVNF",
            "X1BSSUNFEAoSEQoNREVDUkVBU0VfQ09TVBALKnwKD0FJRXZlbnRDYXRlZ29y",
            "eRIaChZOVUxMX0FJX0VWRU5UX0NBVEVHT1JZEAASEgoORUNPTk9NSUNfRVZF",
            "TlQQARIRCg1XRUFUSEVSX0VWRU5UEAISFAoQVEVDSE5PTE9HWV9FVkVOVBAD",
            "EhAKDENPTUJBVF9FVkVOVBAEKm0KCFRhc2tUeXBlEhIKDk5VTExfVEFTS19U",
            "WVBFEAASEwoPUFJPRFVDRV9QUk9EVUNUEAESFAoQSEFSVkVTVF9SRVNPVVJD",
            "RRACEhEKDU9DQ1VQWV9DRU5URVIQAxIPCgtSRVBBSVJfVU5JVBAEKm0KDEFJ",
            "QWN0aW9uVHlwZRILCgdVTktOT1dOEAASCwoHUFJPRFVDRRABEgsKB0hBUlZF",
            "U1QQAhIICgRNT1ZFEAMSCgoGQVRUQUNLEAQSCgoGUkVQQUlSEAUSCAoEU0VM",
            "TBAGEgoKBk9DQ1VQWRAHYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protobuf.GameMode), typeof(global::Protobuf.GameState), typeof(global::Protobuf.PlaceType), typeof(global::Protobuf.ShapeType), typeof(global::Protobuf.PlayerType), typeof(global::Protobuf.CharacterType), typeof(global::Protobuf.CharacterState), typeof(global::Protobuf.HomeState), typeof(global::Protobuf.ComputeCenterState), typeof(global::Protobuf.ResourceState), typeof(global::Protobuf.ResourceType), typeof(global::Protobuf.NewsType), typeof(global::Protobuf.GoodsType), typeof(global::Protobuf.MarketType), typeof(global::Protobuf.TechType), typeof(global::Protobuf.AIEventCategory), typeof(global::Protobuf.TaskType), typeof(global::Protobuf.AIActionType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum GameMode {
    [pbr::OriginalName("NULL_GAME_MODE")] NullGameMode = 0,
    [pbr::OriginalName("GAME_MODE_PVE")] Pve = 1,
    [pbr::OriginalName("GAME_MODE_PVP")] Pvp = 2,
  }

  public enum GameState {
    [pbr::OriginalName("NULL_GAME_STATE")] NullGameState = 0,
    [pbr::OriginalName("GAME_START")] GameStart = 1,
    [pbr::OriginalName("GAME_RUNNING")] GameRunning = 2,
    [pbr::OriginalName("GAME_END")] GameEnd = 3,
  }

  public enum PlaceType {
    [pbr::OriginalName("NULL_PLACE_TYPE")] NullPlaceType = 0,
    /// <summary>
    /// 出生点工厂（地图四个角落）
    /// </summary>
    [pbr::OriginalName("FACTORY")] Factory = 1,
    /// <summary>
    /// 空地
    /// </summary>
    [pbr::OriginalName("SPACE")] Space = 2,
    /// <summary>
    /// 障碍
    /// </summary>
    [pbr::OriginalName("BARRIER")] Barrier = 3,
    /// <summary>
    /// 草丛
    /// </summary>
    [pbr::OriginalName("BUSH")] Bush = 4,
    /// <summary>
    /// 资源
    /// </summary>
    [pbr::OriginalName("RESOURCE")] Resource = 5,
    /// <summary>
    /// 算力中心
    /// </summary>
    [pbr::OriginalName("COMPUTE_CENTER")] ComputeCenter = 6,
    /// <summary>
    /// 市场
    /// </summary>
    [pbr::OriginalName("MARKET")] Market = 7,
  }

  public enum ShapeType {
    [pbr::OriginalName("NULL_SHAPE_TYPE")] NullShapeType = 0,
    [pbr::OriginalName("CIRCLE")] Circle = 1,
    [pbr::OriginalName("SQUARE")] Square = 2,
  }

  public enum PlayerType {
    [pbr::OriginalName("NULL_PLAYER_TYPE")] NullPlayerType = 0,
    [pbr::OriginalName("CHARACTER")] Character = 1,
    [pbr::OriginalName("TEAM")] Team = 2,
  }

  public enum CharacterType {
    [pbr::OriginalName("NULL_CHARACTER_TYPE")] NullCharacterType = 0,
    /// <summary>
    /// 无人机
    /// </summary>
    [pbr::OriginalName("DRONE")] Drone = 1,
    /// <summary>
    /// 机器人
    /// </summary>
    [pbr::OriginalName("ROBOT")] Robot = 2,
    /// <summary>
    /// 无人驾驶汽车
    /// </summary>
    [pbr::OriginalName("AUTONOMOUS_CAR")] AutonomousCar = 3,
  }

  public enum CharacterState {
    [pbr::OriginalName("CHARACTER_STATE_NONE")] None = 0,
    [pbr::OriginalName("CHARACTER_STATE_IDLE")] Idle = 1,
    [pbr::OriginalName("CHARACTER_STATE_HARVESTING")] Harvesting = 2,
    [pbr::OriginalName("CHARACTER_STATE_ATTACKING")] Attacking = 3,
    [pbr::OriginalName("CHARACTER_STATE_OCUPPYING")] Ocuppying = 4,
    [pbr::OriginalName("CHARACTER_STATE_TRADING")] Trading = 5,
    [pbr::OriginalName("CHARACTER_STATE_MOVING")] Moving = 6,
    [pbr::OriginalName("CHARACTER_STATE_KNOCKED_BACK")] KnockedBack = 7,
    [pbr::OriginalName("CHARACTER_STATE_DECEASED")] Deceased = 8,
  }

  public enum HomeState {
    [pbr::OriginalName("NULL_HOME_STATE")] NullHomeState = 0,
    /// <summary>
    /// 闲置状态
    /// </summary>
    [pbr::OriginalName("HOME_STATE_IDLE")] Idle = 1,
    /// <summary>
    /// 生产产品中
    /// </summary>
    [pbr::OriginalName("HOME_STATE_PRODUCING_PRODUCT")] ProducingProduct = 2,
    /// <summary>
    /// 修理中
    /// </summary>
    [pbr::OriginalName("HOME_STATE_REPAIRING")] Repairing = 3,
    /// <summary>
    /// 生产机器中
    /// </summary>
    [pbr::OriginalName("HOME_STATE_PRODUCING_CHARACTER")] ProducingCharacter = 4,
  }

  public enum ComputeCenterState {
    [pbr::OriginalName("NULL_COMPUTE_CENTER_STATE")] NullComputeCenterState = 0,
    [pbr::OriginalName("OCCUPYABLE")] Occupyable = 1,
    [pbr::OriginalName("OCCUPIED")] Occupied = 2,
    [pbr::OriginalName("ROBBED")] Robbed = 3,
  }

  public enum ResourceState {
    [pbr::OriginalName("NULL_ECONOMY_RESOURCE_STSTE")] NullEconomyResourceStste = 0,
    [pbr::OriginalName("HARVESTABLE")] Harvestable = 1,
    [pbr::OriginalName("BEING_HARVESTED")] BeingHarvested = 2,
    [pbr::OriginalName("HARVESTED")] Harvested = 3,
  }

  public enum ResourceType {
    [pbr::OriginalName("NULL_RESOURCE_TYPE")] NullResourceType = 0,
    [pbr::OriginalName("SMALL_RESOURCE")] SmallResource = 1,
    [pbr::OriginalName("MEDIUM_RESOURCE")] MediumResource = 2,
    [pbr::OriginalName("LARGE_RESOURCE")] LargeResource = 3,
  }

  public enum NewsType {
    [pbr::OriginalName("NULL_NEWS_TYPE")] NullNewsType = 0,
    [pbr::OriginalName("TEXT")] Text = 1,
    [pbr::OriginalName("BINARY")] Binary = 2,
  }

  public enum GoodsType {
    [pbr::OriginalName("NULL_GOODS_TYPE")] NullGoodsType = 0,
    [pbr::OriginalName("SEMICONDUCTOR")] Semiconductor = 1,
    [pbr::OriginalName("MEDICINE")] Medicine = 2,
    [pbr::OriginalName("TOYS")] Toys = 3,
    [pbr::OriginalName("CLOTHES")] Clothes = 4,
    [pbr::OriginalName("FOOD")] Food = 5,
  }

  public enum MarketType {
    [pbr::OriginalName("NULL_MARKET_TYPE")] NullMarketType = 0,
    [pbr::OriginalName("SMALL_MARKET")] SmallMarket = 1,
    [pbr::OriginalName("MEDIUM_MARKET")] MediumMarket = 2,
    [pbr::OriginalName("LARGE_MARKET")] LargeMarket = 3,
  }

  public enum TechType {
    [pbr::OriginalName("NULL_TECH_TYPE")] NullTechType = 0,
    [pbr::OriginalName("INCREASE_HP")] IncreaseHp = 1,
    [pbr::OriginalName("INCREASE_ATTACK_POWER")] IncreaseAttackPower = 2,
    [pbr::OriginalName("INCREASE_ATTACK_SIZE")] IncreaseAttackSize = 3,
    [pbr::OriginalName("INCREASE_ROBUST")] IncreaseRobust = 4,
    [pbr::OriginalName("INCREASE_MOVE_SPEED")] IncreaseMoveSpeed = 5,
    [pbr::OriginalName("INCREASE_CARRY_CAPACITY")] IncreaseCarryCapacity = 6,
    [pbr::OriginalName("INCREASE_EFFICIENCY")] IncreaseEfficiency = 7,
    [pbr::OriginalName("INCREASE_PRODUCTION")] IncreaseProduction = 8,
    [pbr::OriginalName("INCREASE_STORAGE")] IncreaseStorage = 9,
    [pbr::OriginalName("INCREASE_PRICE")] IncreasePrice = 10,
    [pbr::OriginalName("DECREASE_COST")] DecreaseCost = 11,
  }

  public enum AIEventCategory {
    [pbr::OriginalName("NULL_AI_EVENT_CATEGORY")] NullAiEventCategory = 0,
    /// <summary>
    /// 价格变化类
    /// </summary>
    [pbr::OriginalName("ECONOMIC_EVENT")] EconomicEvent = 1,
    /// <summary>
    /// 天气影响
    /// </summary>
    [pbr::OriginalName("WEATHER_EVENT")] WeatherEvent = 2,
    /// <summary>
    /// 科技波动
    /// </summary>
    [pbr::OriginalName("TECHNOLOGY_EVENT")] TechnologyEvent = 3,
    /// <summary>
    /// 战斗修正
    /// </summary>
    [pbr::OriginalName("COMBAT_EVENT")] CombatEvent = 4,
  }

  public enum TaskType {
    [pbr::OriginalName("NULL_TASK_TYPE")] NullTaskType = 0,
    [pbr::OriginalName("PRODUCE_PRODUCT")] ProduceProduct = 1,
    [pbr::OriginalName("HARVEST_RESOURCE")] HarvestResource = 2,
    [pbr::OriginalName("OCCUPY_CENTER")] OccupyCenter = 3,
    [pbr::OriginalName("REPAIR_UNIT")] RepairUnit = 4,
  }

  public enum AIActionType {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("PRODUCE")] Produce = 1,
    [pbr::OriginalName("HARVEST")] Harvest = 2,
    [pbr::OriginalName("MOVE")] Move = 3,
    [pbr::OriginalName("ATTACK")] Attack = 4,
    [pbr::OriginalName("REPAIR")] Repair = 5,
    [pbr::OriginalName("SELL")] Sell = 6,
    [pbr::OriginalName("OCCUPY")] Occupy = 7,
  }

  #endregion

}

#endregion Designer generated code
